### ISSUE TITLE
`nest.ResetKernel()` resets installed modules

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nestml#1054]
Hello!

Passing from NESTML 7.0 and NEST 3.6 to current master NESTML and NEST 3.7 introduced this change in the behaviour.

If you execute `nest.ResetKernel()` after having loaded (`nest.Install()`) your NESTML-compiled module makes the module uninstalled.

E.g., you can't use the neuron models installed with the new module unless you re-run `nest.Install()`

Before this was not happening, the model was staying installed and if you tried to re-run `nest.Install()` you got the `"Module '...' is loaded already` error.

You can test running for instance:

```
nest.Install(your_module)
nest.ResetKernel()
nest.Install(your_module)
```

Is this wanted or not? I am not sure if this is more a NESTML or a NEST thing.

**Comment by alberto-antonietti** [comment]
CC @rbonometto

**Comment by clinssen** [comment]
Hi Alberto, this is indeed true! It is related to the change in NEST Simulator (https://github.com/nest/nest-simulator/pull/3103) and was introduced in NESTML 7.0.1 (see the release notes at https://github.com/nest/nestml/releases). Sorry, but your scripts will need to be adjusted going forward.

**Comment by alberto-antonietti** [comment]
Hi Charl, perfect, thanks for the info! Will take this into account and adapt our scripts!
