### ISSUE TITLE
Fixing the type of psc initial value.

### ISSUE THREAD

**Issue by DimitriPlotnikov** [nest/nestml#292]
Test to reproduce: org.nest.integration.NestmlFrontendIntegrationTest#testTutorialModels
Issue:
`32_rc_alpha : WARNING: NESTML_LITERALS_MUST_HAVE_TYPES: Assignment of a literal to a UNIT type variable must carry a Unit Symbol at 32_rc_alpha.nestml:<56,4>`

@PTraeder Can you fix the type of the variable PSConInit_E (line 34) s.t. the assignment at line 56 becomes correct?

**Comment by PTraeder** [comment]
Is fixed in pending commit.

Opening follow-up issue regarding buffer types.

**Comment by DimitriPlotnikov** [comment]
Fixed in #297
