### ISSUE TITLE
Lexer for NestML

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#303]
This is really just some kind of a bonus, but I'm not a great fan of Emacs, so I was wondering how difficult it would be to provide a Scintilla lexer for NestML, which would provide people working with it or Geany get the exact syntax highlighting when working on .nestml files.

**Comment by DimitriPlotnikov** [comment]
@Silmathoron what do you mean with lexer? NESTML is defined by whole bunch of lexer and parser rules in Antlr4. I can render you a set of all keywords.

**Comment by Silmathoron** [comment]
Well, at the first NESTML workshop you said you'd written a lexer for syntax highlighting and autocompletion for emacs.
I was wondering whether it would be possible to have the same thing for [Scintilla](http://www.scintilla.org/Lexer.txt).
I'm working with Geany, where you can base a custom filetype on an existing Scintilla [lexer](http://www.geany.org/manual/current/index.html#lexer-properties-section) (e.g. [Javascript for JSON](https://wiki.geany.org/config/json)), but NESTML does work too well with existing lexers, though the Python lexer gives reasonable results.

**Comment by DimitriPlotnikov** [comment]
Hi,

no I didn't. We have/had an Eclipse plugin. And it highlighted keywords based on keywords, which works well for context free languages which NESTML is. Lexer does a little bit more than this simple highlighting scheme. Therefore, depending on what you precisely want I can try to extract this information from NESTML code.

**Comment by Silmathoron** [comment]
Ok, it's still a work in progress, but it's almost good (only auto-indent to go)
![nestmllexer](https://cloud.githubusercontent.com/assets/8523051/21294847/a2e62872-c547-11e6-9418-d78a9163c236.png)

**Comment by clinssen** [comment]
@Silmathoron: thanks for this! I'm thinking about how to best integrate this into the NESTML repository. Unfortunately it seems that a good standard for syntax highlighting does not exist: almost each editor defines its own format to define the syntax highlighting rules.

So, to make this into a workable solution, I suggest the following. The `tools` directory in the root at present only contains another directory called `codeanalysis`. I suggest:
1. renaming `tools` to `extras` (similar to https://github.com/nest/nest-simulator)
1. making a directory `extras/syntax_highlighting` where we could place all the necessary files for different editors. People could contribute support for their favourite editor by filing a PR that places the necessary file in this directory.

Please let me know what you think, and if you'd like to file this PR for geany after we create the directory structure!

**Comment by Silmathoron** [comment]
@clinssen this sounds nice!
The thing is: this was an old project and I never made a PR for it... (on the geany repo, that is)
I can provide a small config file for geany, which will take care of syntax highlighting (nothing more, and not too well), but I think the best thing to do here would be to provide a Scintilla lexer (unfortunately I don't have time to do it).

Once you make the changes to the folder, mention me in the PR and I'll update the syntax highlighting file, then make a PR to include it.

BTW, I kind of lost track of NESTML these past months (years): are we stable, API-wise, in terms of keywords, units, etc?

**Comment by Silmathoron** [comment]
This is now on review in PR #509

**Comment by clinssen** [comment]
Closing as #509 has been merged.
