### ISSUE TITLE
Change Units.mc4 to accept literal "1" in place of a full unit in nominators?

### ISSUE THREAD

**Issue by PTraeder** [nest/nestml#305]
@DimitriPlotnikov  You have remarked on how you want to enable literals to occur in the nominator of unit declarations, i.e. instead of writing:

SomeVar ms**-1 = 5/ ms

we could then write:

SomeVar 1/ms = 5/ms

After finishing up my refactoring of the prettyprinting of units, the generated output has this format in case no nominator can be identified.
I would now have to implement changes to the grammar resulting in the above behaviour in order to have models with generated nestml portions be parsable.

I propose the following change to the UnitType Nonterminal in Units.mc4:

  UnitType = leftParentheses:"(" UnitType rightParentheses:")"
           | base:UnitType pow:["**"] exponent:IntLiteral
           | left:UnitType (timesOp:["*"] | divOp:["/"]) right:UnitType
           | unitlessLiteral:"1" divOp:["/"] right:UnitType
           | unit:Name;

(only the second to last option has been added)

As far as my understanding of MC goes, this should enable us to use declarations of the mentioned style while simultaneously ensuring that the literal used will always only be "1" without the need for an additional CoCo.

What do you think?

**Comment by PTraeder** [comment]
This change makes the parser fail to recognize expressions correctly. Going to look into this further tomorrow.

**Comment by DimitriPlotnikov** [comment]
@PTraeder it seems to be done now?

**Comment by PTraeder** [comment]
Yes, changed to expect a IntLiteral and implemented a Coco to check that said literal is always '1'
