### ISSUE TITLE
Explicit units for "sum" functions

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#324]
Currently, there are some problems with ``_sum`` functions in NESTML:
*  ``spikes.get_sum()`` delivers ``pA``, whereas it should deliver ``real``
*  ``cond_sum`` seems not to deliver ``nS`` (I don't know what it does)
* neither does ``curr_sum()`` seem to deliver ``pA``

Maybe I should be more explicit about the first problem:
* we use normalization functions for the alpha model to make sure the peak is at ``1 pA`` times the "synaptic weight" (dimensionless)
* for ``_exp`` models, the dimensionless property can either be handled by the Unit+primitive=unit property of #317 or if we treat dimension mismatches as errors, the user will have to specify by hand ``g += 1 nS * spikes.get_sum()``

**Comment by DimitriPlotnikov** [comment]
@PTraeder Can you check it?

**Comment by PTraeder** [comment]
Fixed in #328
