### ISSUE TITLE
Problem with *=

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#325]
In ``mat2_psc_exp.nestml``, current implementation leads to the following error:

    mat2_psc_exp : WARNING: SPL_ILLEGAL_EXPRESSION <118,4> : Attempting to assign real to variable V_th_alpha_1 with type mV
    mat2_psc_exp : WARNING: SPL_ILLEGAL_EXPRESSION <119,4> : Attempting to assign real to variable V_th_alpha_2 with type mV

which corresponds to lines

    V_th_alpha_1 *= P11th
    V_th_alpha_2 *= P22th

Which seems to mean (given that both ``P11th`` and ``P22th`` are of type ``real``) that unit check for ``*=`` is not handled correctly

**Comment by DimitriPlotnikov** [comment]
Yes, but V_th_alpha_1 is of the type `mV`. It is also said in the error description.

**Comment by Silmathoron** [comment]
I don't understand what you mean: if ``V_th_alpha`` is of type ``mV`` and ``P11th`` is ``real`` then:

``V_th_alpha_1 *= P11th`` means ``V_th_alpha_1 = P11th* V_th_alpha_1``

which leads to, for the units, ``[V] <- [V]*[1] = [V]`` which is coherent so should not raise any error...

**Comment by PTraeder** [comment]
@Silmathoron is correct. Assignment checks have just been implemented and the *=,+=,/=,-= operators are not checked _at_all_ including primitive types.

**Comment by PTraeder** [comment]
Implemented compound assignments in #328

**Comment by PTraeder** [comment]
Can we close this? @Silmathoron @DimitriPlotnikov
