### ISSUE TITLE
Initiate derivative of state variables

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#326]
For implicit alpha-shaped functions, we need to initialize the derivative.
However, currently:

    I_ex' pA/ms = 0. pA/ms

or 

    g_ex' nS/ms = 0. nS/ms

Leads to the following error:

    ERROR: The artifact is unparsable: <Optional[aeif_cond_alpha_implicit.nestml:<40,8>]>: extraneous input ''' expecting {'void', 'boolean', 'integer', 'real', 'string', '(', ',', '-', Name, Num_Int}

**Comment by DimitriPlotnikov** [comment]
Yes, ti is correct. Use square brackets 0.[pA/ms]

**Comment by Silmathoron** [comment]
Maybe I did not understand correctly, but

    I_syn_ex' [pA/ms] = 0. [pA/ms]

does not work either...

**Comment by DimitriPlotnikov** [comment]
@Silmathoron 
Ok, yes. 
This syntax is under development. Can you please post the whole model?

**Comment by Silmathoron** [comment]
E.g. change the ``state`` block of ``aeif_cond_alpha_implicit.nestml`` into:

    state:
        V_m mV = E_L      # Membrane potential
        w pA = 0 pA        # Spike-adaptation current
        g_in nS = 0 nS     # Excitatory synaptic conductance
        g_ex nS = 0 nS     # Inhibitory synaptic conductance in nS
        g_in' nS/ms = 0 [nS/ms]     # First derivative of excitatory synaptic conductance
        g_ex' nS/ms = 0 [nS/ms]     # First derivative of inhibitory synaptic conductance
    end

**Comment by PTraeder** [comment]
The problem here are not the types but the fact that the grammar does not expect derivatives in declarations. Only inside equations blocks and expressions will the parser accept them.

**Comment by Silmathoron** [comment]
@PTraeder Is there a way to change this and support derivatives inside ``state``?

**Comment by DimitriPlotnikov** [comment]
@Silmathoron 
Yes, we have an meeting this week to implement proper support for initial values.

**Comment by kperun** [comment]
Issue closed, since initial values already included.
