### ISSUE TITLE
Unable to run example models under Docker

### ISSUE THREAD

**Issue by hyukz** [nest/nestml#349]
NestML installation via Docker will not run any of the models provided as examples. Error list is extensive and I've only listed the outputs for three models below.

**System:** Antergos (Arch Linux) and MacOS Sierra
**Branch:** master (last commit 0e5ad3c)

>Running docker image 'nestml_release'
INFO: The input modelpath: /models
INFO: The base output path: /models/build
INFO: Correct python version is installed
INFO: Correct SymPy is installed.
06:05:35.169 [main] ERROR ROOT - iaf_cond_exp.nestml:<36,13>: mismatched input 'I_syn_exc' expecting {''', '.', '='}
06:05:35.181 [main] ERROR ROOT - iaf_cond_exp.nestml:<37,13>: mismatched input 'I_syn_inh' expecting {''', '.', '='}
06:05:35.183 [main] ERROR ROOT - iaf_cond_exp.nestml:<38,13>: mismatched input 'I_leak' expecting {''', '.', '='}
06:05:35.268 [main] ERROR ROOT - iaf_cond_beta.nestml:<38,15>: mismatched input 'I_syn_exc' expecting {''', '.', '='}
06:05:35.270 [main] ERROR ROOT - iaf_cond_beta.nestml:<39,15>: mismatched input 'I_syn_inh' expecting {''', '.', '='}
06:05:35.271 [main] ERROR ROOT - iaf_cond_beta.nestml:<40,15>: mismatched input 'I_leak' expecting {''', '.', '='}
06:05:35.301 [main] ERROR ROOT - iaf_neuron.nestml:<78,4>: extraneous input 'function' expecting {'end', 'recordable', 'alias', Name, NEWLINE}
06:05:35.304 [main] ERROR ROOT - iaf_neuron.nestml:<78,17>: missing '(' at 'mV'
06:05:35.307 [main] ERROR ROOT - iaf_neuron.nestml:<78,20>: no viable alternative at input '='
06:05:35.307 [main] ERROR ROOT - iaf_neuron.nestml:<82,2>: extraneous input 'equations' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.308 [main] ERROR ROOT - iaf_neuron.nestml:<83,4>: extraneous input 'shape' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.308 [main] ERROR ROOT - iaf_neuron.nestml:<84,4>: extraneous input 'V_abs' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.308 [main] ERROR ROOT - iaf_neuron.nestml:<85,2>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.309 [main] ERROR ROOT - iaf_neuron.nestml:<88,2>: extraneous input 'parameters' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.309 [main] ERROR ROOT - iaf_neuron.nestml:<89,4>: extraneous input 'C_m' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.309 [main] ERROR ROOT - iaf_neuron.nestml:<90,4>: extraneous input 'Tau' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.310 [main] ERROR ROOT - iaf_neuron.nestml:<91,4>: extraneous input 'tau_syn' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.310 [main] ERROR ROOT - iaf_neuron.nestml:<92,4>: extraneous input 't_ref' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.310 [main] ERROR ROOT - iaf_neuron.nestml:<93,4>: extraneous input 'E_L' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.310 [main] ERROR ROOT - iaf_neuron.nestml:<94,4>: extraneous input 'function' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.311 [main] ERROR ROOT - iaf_neuron.nestml:<95,4>: extraneous input 'function' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.311 [main] ERROR ROOT - iaf_neuron.nestml:<96,4>: extraneous input 'I_e' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.311 [main] ERROR ROOT - iaf_neuron.nestml:<97,2>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.311 [main] ERROR ROOT - iaf_neuron.nestml:<100,2>: extraneous input 'internals' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.312 [main] ERROR ROOT - iaf_neuron.nestml:<102,4>: extraneous input 'RefractoryCounts' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.312 [main] ERROR ROOT - iaf_neuron.nestml:<104,4>: extraneous input 'r' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.312 [main] ERROR ROOT - iaf_neuron.nestml:<105,2>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.313 [main] ERROR ROOT - iaf_neuron.nestml:<108,2>: extraneous input 'input' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.313 [main] ERROR ROOT - iaf_neuron.nestml:<109,4>: extraneous input 'spikes' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.313 [main] ERROR ROOT - iaf_neuron.nestml:<110,4>: extraneous input 'currents' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.313 [main] ERROR ROOT - iaf_neuron.nestml:<111,2>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.317 [main] ERROR ROOT - iaf_neuron.nestml:<114,2>: extraneous input 'output' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.317 [main] ERROR ROOT - iaf_neuron.nestml:<117,2>: extraneous input 'update' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.318 [main] ERROR ROOT - iaf_neuron.nestml:<118,4>: extraneous input 'if' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.318 [main] ERROR ROOT - iaf_neuron.nestml:<119,6>: extraneous input 'integrate_odes' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.318 [main] ERROR ROOT - iaf_neuron.nestml:<120,6>: extraneous input 'if' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.318 [main] ERROR ROOT - iaf_neuron.nestml:<121,8>: extraneous input 'r' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.319 [main] ERROR ROOT - iaf_neuron.nestml:<122,8>: extraneous input 'V_abs' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.319 [main] ERROR ROOT - iaf_neuron.nestml:<127,8>: extraneous input 'emit_spike' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.319 [main] ERROR ROOT - iaf_neuron.nestml:<128,6>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.319 [main] ERROR ROOT - iaf_neuron.nestml:<129,4>: extraneous input 'else' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.320 [main] ERROR ROOT - iaf_neuron.nestml:<130,6>: extraneous input 'r' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.320 [main] ERROR ROOT - iaf_neuron.nestml:<131,4>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.320 [main] ERROR ROOT - iaf_neuron.nestml:<133,2>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
06:05:35.320 [main] ERROR ROOT - iaf_neuron.nestml:<135,0>: extraneous input 'end' expecting {<EOF>, 'neuron', 'component', NEWLINE}
...

**Comment by DimitriPlotnikov** [comment]
When you generate models from the the master branch, then you must also use the --dev option of the management script.

E.g.:

`./nestml_docker provision --dev`
`./nestml_docker run path_to_models --dev`

**Comment by hyukz** [comment]
Using the --dev option solved my problem. Thank you.

I would suggest giving a greater highlight to the lastest release link (e.g. a link at the beginning of the readme.md). As of now other first time users may download the master branch instead of a release and make the same mistake I did, ending up in a series of errors that in no way are easy to link with the lack of --dev option for a first timer.
