### ISSUE TITLE
"Neuroscience" SI units in NESTML

### ISSUE THREAD

**Issue by DimitriPlotnikov** [nest/nestml#362]
The goal of this discussion is to define a list with "neuroscience" magnitudes of SI in NEST/NESTML. E.g. all variables in NESTML models of the SI unit will be automatically converted to a proper magnitued during the NEST code generation workflow. The current status is. @Silmathoron, @heplesser. @PTraeder: can you update/extend the list since you know what is really supported.
```
milli seconds - ms
pico farad   - pF
milli volt    - mV
pico ampere  - pA
nano siemens - nS
mega ohm     - MOhm
```

**Comment by heplesser** [comment]
The list looks good, but as [@Silmathoron pointed out](https://github.com/nest/nestml/issues/299#issuecomment-305406623), resistance should be in gigaohm, not megaohm. That is also consistent with conductance in nanosiemens.

The only other units I can think of right now are for 
- frequencies: Hz
- rates: s^-1
- angles: deg
Note that frequencies and rates are given per second, not per ms.

**Comment by DimitriPlotnikov** [comment]
@heplesser 
Do we have any NEST models with such units (Hz, s^-1,deg)?

**Comment by Silmathoron** [comment]
Yes, stochastically spiking neurons like [pp_psc_delta](https://github.com/nest/nest-simulator/blob/32fdfd8eab48499cfea33b9cd5832f3b00f1e5f1/models/pp_psc_delta.h#L160)

**Comment by heplesser** [comment]
Almost all `_generator` models except `dc_generator` have some such parameters.

**Comment by Silmathoron** [comment]
Do we plan to extend NESTML to make generators?

**Comment by DimitriPlotnikov** [comment]
In midterm yes. Current prios from my perspective would be : stability of the nest-generator for all kinds of iaf-neurons, support for synapses, remaining types of NEST neurons, re-implementation of NESTML in Python, ...

**Comment by Silmathoron** [comment]
I'm very much looking forward to the last part ;)

**Comment by DimitriPlotnikov** [comment]
Yes, it will take its time. I've a student worker how will start that translation in next months. If you have already any expertise in Python's parser generators, I'll would appreciate your input. We are currently evaluating: pyparsing, ply (+its extensions) and ANTLR4.

**Comment by DimitriPlotnikov** [comment]
Done.
