### ISSUE TITLE
'Unitsoff' feature as in Neuron simulator

### ISSUE THREAD

**Issue by vogdb** [nest/nestml#399]
Is there the same in NestML? For example in Nernst equation we use constants as `R`(gas constant), `F`(faraday constant). Now we need to state their exact units which are enormous although these are used only in Nernst equation. In Neuron we can escape this by putting the equation inside `UnitsOff` block.
Btw I'm not proposing it. I'm just asking.

**Comment by jougs** [comment]
No, this is currently not existing. We thought about introducing a command line switch `--no-unit-checks` or similar in order to remind users constantly that they are doing something dangerous when using it.

@PTraeder: can you please assess how complicated adding such a switch would be? Thanks!
