### ISSUE TITLE
Periodic amplitudes in gating values

### ISSUE THREAD

**Issue by vogdb** [nest/nestml#402]
It's me again. I hope you won't put me into a blacklist of the project :)

I'm implementing a custom HH model from a Neuron simulator implementation. Somehow gating particles `Act_m` and `Inact_n` change their amplitude periodically. `Act_h` behaves fine. For example here how `Inact_n` behaves in Neuron.
![neuron_n](https://github.com/vogdb/neuron-vs-nest/raw/master/neuron_vs_nest/custom_hh/neuron/neuron_n.png)

In Nest it differs
![nest_n](https://github.com/vogdb/neuron-vs-nest/raw/master/neuron_vs_nest/custom_hh/nest/nest_n.png)

The implementation is here https://github.com/vogdb/neuron-vs-nest/blob/master/neuron_vs_nest/custom_hh/nest/custom_hh_model/custom_hh.nestml . Its Neuron simulator counterpart is here 
https://github.com/vogdb/neuron-vs-nest/blob/master/neuron_vs_nest/custom_hh/neuron/custom_hh.mod

**Comment by DimitriPlotnikov** [comment]
Did you try to experiment with nest resolution? E.g. to make the resolution more precise (nest.SetKernelStatus({"resolution":0.01}))?

**Comment by vogdb** [comment]
Yes. The result was the same. Actually just now I've finally rebuilt the model in pure NEST (spent a couple of days on this C++ journey). The result of pure NEST has the same problem. Somehow the same calculations produce the different result.
My amateur neuroscience knowledge is not enough to understand where is the problem so I hoped may be you can help me here :)

**Comment by DimitriPlotnikov** [comment]
I'm not neuroscientist at all. Try to reask it in the nest project issues section.

**Comment by vogdb** [comment]
ok, thanks!

**Comment by vogdb** [comment]
Just for the history. The problem was in `interval` of `multimeter`. It should have been equal to `resolution` of the simulation.
