### ISSUE TITLE
variable define multiple times: How to define state variables

### ISSUE THREAD

**Issue by mschmidt87** [nest/nestml#404]
Hi,
I am having problem with defining a variable in my nestml script. In the attached file, I define the variable `H` which essentially represents the output of the Heaviside function. Its value is computed in every update step in the `update` block. So, I though that I have to initialize this variable in the `state` block, as done in the attached file. However, nestml then complains that 

> The variable H is defined multiple times.

If I remove the line initializing `H` in the `state` block, nestml does not complain.
However, when I then try to compile the generated c++ Files, the compiler complains that 

> error: 'H' was not declared in this scope`

I also tried putting the initialization of `H` in the `initials` block but this does not work either. What is the correct way to go?

[teste.txt](https://github.com/nest/nestml/files/1643927/teste.txt)

**Comment by DimitriPlotnikov** [comment]
Hi!

The variable `H` seems to be a predefined variable (Unit). Can you use a different name?

Other than that. You can give a try to an alternative implementation of Nestml (https://github.com/nest/nestml/tree/PyNestML). Without workaround with docker.

**Comment by mschmidt87** [comment]
Thanks, this solved the problem.
