### ISSUE TITLE
Simple equation without derivatives. Please a bit of advice.

### ISSUE THREAD

**Issue by vogdb** [nest/nestml#409]
Hi, dear Nestml contributors. Please share your wisdom when you have a spare minute.

I want to implement a simple model of IAF neuron from Neuron simulator: [IntFire1](https://www.neuron.yale.edu/neuron/static/docs/help/neuron/neuron/mech.html#IntFire1)
It has a very simple math.
- When it does not receive any input it decreases its voltage according to this:
  ```
  V_1 = V_0 * exp(-(t_1 - t_0)/tau), V_0 - previous value of voltage, V_1 - new value of voltage.
  ```
- When it receives a spike, it just adds its weight
  ```
  V = V + spikes
  ```

What block would be appropriate to choose? Would be `update` enough? I can't access `t` there. Also I can't access `t` in `equations` directly, only as a part of `shape`.

**Comment by vogdb** [comment]
@DimitriPlotnikov or @PTraeder please any hint here or in #408

**Comment by DimitriPlotnikov** [comment]
Hi,

till now I didn't have use cases. Please, scatch a complete nestml model you would like to work and we can work out a possible implementation/generation scheme.

Regarding time variable t:
I can provide you `t` in the update block. I think it is also possible (technically it is easy to use) to use time variable in the equation block

**Comment by vogdb** [comment]
Hi! Thank you for the response.
Here is a draft of the model I intend to create. I put the `V_m` equation to `equations`. However it does not contain any derivatives.
```
neuron int_fire1:

  initial_values:
    V_m real = 0.
  end

  parameters:
    tau real = 2.
  end

  equations:
    # V_m just decreases with time without any derivatives.
    # `t1` is the current time.
    # `t0` is an infinitesimal time before `t1`.

    V_m = V_m * exp(-(t1-t0)/tau)
  end

  input:
    spikes mV <- spike
    currents <- current
  end

  output: spike

  update:
    integrate_odes()

    # we add spike as it is
    V_m += spikes
    t_ref = t

    # threshold crossing
    if V_m > 1.:
      V_m = 0
      emit_spike()
    end

  end

end
```

**Comment by vogdb** [comment]
@DimitriPlotnikov what adjusts would you recommed?
