### ISSUE TITLE
stale version number in message string

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#429]
https://github.com/nest/nestml/blob/a53867178246ca58fbfed8f9942259f1020b0d45/pynestml/frontend/frontend_configuration.py#L75

**Comment by clinssen** [comment]
@jougs: I know you did some magic extracting the always-latest NEST version number for use in this kind of situation. Unfortunately most of the magic seems to be written in SLI. Is there a design pattern, or similar best practice that we can follow?

**Comment by jougs** [comment]
The code that does the magic is actually a pretty plain bash script: [extras/create_rcsinfo.sh](https://github.com/nest/nest-simulator/blob/master/extras/create_rcsinfo.sh). We set the version to a fixed string and then try to come up with a git tag or latest commit that we can use instead, if the sources are not from a tarball.

**Comment by clinssen** [comment]
What we could do is the following:
- Maintain a NESTML version number in no more than two places, e.g. in the README and in one of the Python files (perhaps as `pynestml.__version__`)
- I will file a PR to set these strings to "3.0-dev" (3.0 is the latest release according to the GitHub releases page). The "dev" ensures that people do not pull the master branch and mistake it for the 3.0 release.
- When we do a release, we file a PR to put the new version number in (e.g. "3.1"), do the release, then file a second PR to add the "-dev" suffix back into master.

The last step is obviously where things get a little tedious, but let me know if you think this is a workable solution, or if you have a much better suggestion altogether!

**Comment by jougs** [comment]
I like your suggestion. Please feel free to implement it. I'll happily review and accept a corresponding PR.

**Comment by clinssen** [comment]
Fixed by PR #433
