### ISSUE TITLE
‘nest::DynamicLoaderModule’ has not been declared

### ISSUE THREAD

**Issue by tfburns** [nest/nestml#455]
After installation and resolving a different compile issue (https://github.com/nest/nestml/pull/438#issuecomment-463607271), I get another error when attempting to compile the provided `iaf_cond_exp.nestml` model.

Here is the output of `make all`

> make all
Scanning dependencies of target nestmlmodule_module
[ 12%] Building CXX object CMakeFiles/nestmlmodule_module.dir/nestmlmodule.cpp.o
[ 25%] Building CXX object CMakeFiles/nestmlmodule_module.dir/iaf_cond_exp.cpp.o
[ 37%] Building CXX object CMakeFiles/nestmlmodule_module.dir/iaf_cond_exp_implicit.cpp.o
[ 50%] Linking CXX shared module nestmlmodule.so
[ 50%] Built target nestmlmodule_module
Scanning dependencies of target generate_help
Extracting help information; this may take a little while.
Extracting help information. This may take a little while.
[ 50%] Built target generate_help
Scanning dependencies of target nestmlmodule_lib
[ 62%] Building CXX object CMakeFiles/nestmlmodule_lib.dir/nestmlmodule.cpp.o
/home/tom/Desktop/exp/nestmlmodule.cpp: In constructor ‘nestmlmodule::nestmlmodule()’:
/home/tom/Desktop/exp/nestmlmodule.cpp:85:9: error: ‘nest::DynamicLoaderModule’ has not been declared
   nest::DynamicLoaderModule::registerLinkedModule( this );
         ^~~~~~~~~~~~~~~~~~~
CMakeFiles/nestmlmodule_lib.dir/build.make:62: recipe for target 'CMakeFiles/nestmlmodule_lib.dir/nestmlmodule.cpp.o' failed
make[2]: *** [CMakeFiles/nestmlmodule_lib.dir/nestmlmodule.cpp.o] Error 1
CMakeFiles/Makefile2:173: recipe for target 'CMakeFiles/nestmlmodule_lib.dir/all' failed
make[1]: *** [CMakeFiles/nestmlmodule_lib.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by clinssen** [comment]
It appears that it is having trouble finding the necessary header in NEST. This sounds like an issue with installation. Could you try to clear the cmake cache, make clean, and check your paths?

**Comment by tfburns** [comment]
Hi @clinssen , apologies but I had to give up on this and simulate ODEs directly. Unideal, but works for now, and arguably provides much more flexibility.

**Comment by clinssen** [comment]
OK, thanks for the feedback, please let us know if we can provide any further support to make things work in NESTML.
