### ISSUE TITLE
ODE Toolbox requirement

### ISSUE THREAD

**Issue by sebastianberns** [nest/nestml#464]
The [requirements](https://github.com/nest/nestml/blob/master/requirements.txt) list the ODE toolbox.

But the referenced repository is https://github.com/DimitriPlotnikov/ode-toolbox, which is a (apparently slightly outdated) fork of https://github.com/nest/ode-toolbox. How do the two differ?

**Comment by clinssen** [comment]
Hi, thanks for pointing this out! The differences are minor, but the version on the NEST account is slightly more up-to-date. I've updated the links in #465.
