### ISSUE TITLE
Shapes and functions

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#478]
I am currently trying to understand why, now that ``function``s exist, we still need the ``shape`` object.

I see two main issues with it:

- it is less intuitive than ``function`` for new users
- it does not accept a return type

This is typically problematic when used with the ``convolve`` function because types are inconsistent unless the proper unit is added.

Shouldn't we just get rid of the ``shape`` and replace it with ``function`` altogether?
(I guess we can still implement the proposed template in #373 to functions instead of shapes)

**Comment by clinssen** [comment]
Hi @Silmathoron, thanks for your proposal! In general I'm always in favour of simplifications and making the end user experience more intuitive. One question: do you have a suggestion for how to deal with shapes that are defined as a differential equation, e.g.

    shape g_in'' = ...

**Comment by Silmathoron** [comment]
@clinssen I had forgotten about that...
Does this feature support differential equations which do not have an analytic solution?
If so, then yes, we need to find a way to still provide this feature, otherwise I would just propose to drop it.

**Comment by Silmathoron** [comment]
To be honest we can also just use

```
function g_in''(optional params) nS/ms**2  = ...
```

to declare a function through a differential equation.

**Comment by clinssen** [comment]
A related issue is that shapes are untyped (actually, their type is always assumed to be Real). This is causing some typing errors after AST rewriting, when shape names are replaced by their declaring expressions. As NESTML functions are already typed, merging the shape and function concepts would eliminate this issue.
