### ISSUE TITLE
Detect incorrect variable name

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#481]
I spent a whole afternoon debugging a very stupid problem (which was therefore very difficult to find): NESTML has a weird behavior when a variable name corresponds to a unit or magnitude prefix.

For instance I was using `k` as function argument and it was replaced by `1.0` in the generated C++ code.

I think it would be useful to check variable names to make sure that they do not correspond to either a unit or a magnitude (or any other predefined symbol), and raise an error if it does.

**Comment by clinssen** [comment]
If all is well, you should receive a warning message for this, e.g.:

    [3,test, WARNING, [5:4;5:13]]: Variable 's' has the same name as a physical unit!

We could turn this into an error instead of warning, but note that there are very many physical units defined, so conflicts are probable. At any rate, erroring out is probably better than having unintuitive downstream consequences.

**Comment by Silmathoron** [comment]
@clinssen what is the default log level?
Currently I get no warning for this if I replace ``k_t`` by ``k``, but every occurrence of ``k`` inside the C++ code of the function will be replaced by ``1.0``.

```
  function tau_shape(tau_y ms, V_m mV, Vh mV, k_t mV) ms:
    arg_exp real = clip(-(V_m-Vh)/k_t, -50., 50.)
    res       ms = clip(tau_y/cosh(arg_exp), 1e-10*ms, tau_y)*ms
    return res
  end
```

Similarly, I got no warning when using ``V`` instead of ``V_m`` for the membrane potential (but obviously the C++ code doesn't work.

**Comment by Silmathoron** [comment]
It appears that this issue is still occurring with the GSL solver (@clinssen is on it).
Furthermore, regardless of whether we fix it or not, there is a more general problem:

* there are *many* units defined in astropy, so clashes are almost certain
* if a user uses a variable named as a unit (e.g. ``G``), then how do we know whether he is actually also using the unit ``G`` inside the file (admittedly this would be rather stupid, but well...)

Current option is to raise a warning and consider that all occurrences are the variable unless it crashes. My only issue with it is that the current log level is error.

Various options are:

1. raise an error (but this will be annoying for the users because it *will* happen (often)
2. check the whole file to see if the unit is also used (from a declaration, e.g. ``foo G = bar``) and only raise an error if this happens
3. really check everything and figure it out based on the dimension analysis (unless ``G`` has unit ``G``)

I would be in favor of either keeping the current solution and lowering the log level or using 2. but I think this deserves a proper discussion.

**Comment by Silmathoron** [comment]
Bug was fixed by #495 merge

**Comment by clinssen** [comment]
@Silmathoron: Just to double-check: can we close this issue?

**Comment by Silmathoron** [comment]
@clinssen did we have a proper discussion about the [points I raised](https://github.com/nest/nestml/issues/481#issuecomment-499096366)? And if so what did we decide? I must say I don't remember discussing it in any way...

**Comment by clinssen** [comment]
The current heuristic for ambiguity between variable names and physical units is as follows: try to parse the token as a variable name (or shape, or function name); if this fails, try to parse it as a physical unit. A warning will be issued for each occurrence of an ambiguity (including line number).

I will in any case add this explanation to `doc/nestml_language.md` before closing this issue.

**Comment by Silmathoron** [comment]
@clinssen if you get a success for a variable parse (let's say ``G`` was successfully parsed as a variable on line 5), but ``G`` is used as unit on line 8 (so unit failure on that line trying to parse as variable, but can be correctly parsed as unit), is an error raised?

**Comment by clinssen** [comment]
Basically, for every occurrence of a symbol, PyNestML will try to resolve the symbol (`Scope.resolve_to_symbol(sym_name)`). It will first try to resolve it as a variable, and only if this fails, will it try to resolve it as a physical unit. So if you defined a shape, variable or parameter "G", then all subsequent uses of this symbol "G" will refer to the variable and not the physical unit by precedence.

**Comment by Silmathoron** [comment]
OK, that's fine with me, you can close this as soon as the behavior is documented :+1:
