### ISSUE TITLE
Merge of to_nest() and nest_install()

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#503]
`to_nest()` requires the user to specify the directory where generated code will be written into. The same directory needs to be specified as a parameter to `install_nest()`. If these functions are merged, and the user does not particularly care where the model is generated, there should be no need to specify a target path.

The target location should default to a place where NEST can find the generated `.so` file without additional specification of `LD_LIBRARY_PATH`. Possibly, `nest-config` should be interrogated for the requisite path.

**Comment by Silmathoron** [comment]
See also #480

**Comment by clinssen** [comment]
One potential solution could be:
- rename ``to_nest(...)`` to ``generate_target_code(target="nest", ...)``
- rename ``install_nest(...)`` to ``build_target_code(target="nest", ...)``
- add a new function ``generate_build_target_code(target="nest", ...)`` that simply calls the first two in order.

Side points:
- ``pynestml/utils/model_installer.py`` is NEST-specific and should be moved to ``pynestml/codegeneration`` (or a subdirectory in there)
- same for NEST-specific functions in ``pynestml/frontend/pynestml_frontend.py``

**Comment by tfardet** [comment]
Are there plans to make NESTML not NEST specific? Given the name this seems like a strange idea ^^"
If not, then I would rather try to avoid breaking all user codes...
I'd be fine with adding a new function combining both previous functions without renaming them, though
