### ISSUE TITLE
Many models are not working

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#505]
I don't know what the current unittests are checking, but many models (e.g. ``aeif_cond_alpha``) are currently not being compiled by NESTML on the current master (428cb97c8ba0f1b4e69b1cd0b7d48f5106b1e1ea).
The first issue is associated to the convolve function which has no proper units (because ``shape``s don't have any) but even when this issue is fixed, the code-generation stops with the following message:

    Only shapes provided. Return ODE representation with IV.

Therefore, I think making sure that all models are properly associated to a generated C++ code should be the first priority for the unittests.
This message might also be converted to an error in the future...

**Comment by clinssen** [comment]
Hi @Silmathoron, thanks for emphasising the need for integration tests with NEST Simulator. I will try to look at this today. However, I could not reproduce your results: the aeif_cond_alpha model generates C++ code fine, and the C++ code compiles and builds fine, too. Could you post full log and version information (also for odetoolbox)? Thanks!

**Comment by Silmathoron** [comment]
Thanks for the quick reply @clinssen 
I forgot to update odetoolbox so apparently everything works now.

Also I realized that apparently the message is not an error since it still appears so I guess it means that the codegenerator is converting the shapes to ODEs... maybe a reformulation would be necessary to make it clearer, something like:

    Shapes successfully converted to ODEs.

And move it to the normal logging format, probably at INFO level.

Overall, sorry for the noise ;)

**Comment by clinssen** [comment]
No worries—I am working on improving the Travis CI testing and setting up integration tests now, so there is a definite upshot to this! We are a few weeks away from launching the new ode-toolbox, which will make all related processing a lot more smooth.

**Comment by Silmathoron** [comment]
Also I was wondering: since the purpose of the the codegenerator is to generate the code (sorry for stating this), is it really a good idea for the success message to be at INFO level?
Shouldn't we maybe just print it and add a "silent" option at NESTML level or just to the function as a separate option?

**Comment by clinssen** [comment]
I'm not sure I'm following; isn't this covered by `--logging_level=NONE`? The extraneous ode-toolbox output will be eliminated in the next release.

**Comment by Silmathoron** [comment]
My point is shouldn't the "SUCCESS" message be printed all the time (not as logging) unless the user really wants NESTML to be completely quiet?

**Comment by clinssen** [comment]
The default logging level is ERROR, so the current philosophy is indeed to not output any text whatsoever on success. Probably, all text that is printed should go via the logger. I believe this to be consistent with unix philosophy, but am open to arguments to the converse.

**Comment by Silmathoron** [comment]
I guess we could create an additional level that would have an even higher priority than ERROR, and would be called something like MESSAGE, so important information such as success messages still appear at the default ERROR level

**Comment by Silmathoron** [comment]
I just meant that keeping the success message at INFO level means that they are basically never visible even though they are the most important (at least to my mind)
