### ISSUE TITLE
Create "documentation" block for reStructuredText model documentation

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#513]
Presently, the model documentation is supplied as a comment block `/* ... */` on the lines just before the `neuron` keyword. We propose to continue supporting this comment syntax for inline NESTML model comments, but to move the main model documentation (in reStructuredText format) to a new NESTML block called `documentation`.

The NESTML model might require indentation, that applies within the .nestml file but does not make sense for a section of reStructuredText in isolation. For example, a user might want to indent the entire documentation block within the NESTML model, but a line starting with whitespace is interpreted as a block comment in RST. The block can be automatically dedented by calling Python `textwrap.dedent()`.

**Comment by Silmathoron** [comment]
@clinssen I'm not sure I am very enthusiastic about this...
First of all, I would remove ``/* */`` altogether and replace it with ``""" """`` to be coherent with our python-like syntax.
Secondly, I find the current presentation more attractive since a) it comes first b) it reduces the indentation level and c) it requires no additional structure and is more or less in line with general coding conventions on documentation

**Comment by jougs** [comment]
I like the `""" """` suggestion quite a bit. 

For NESTio, I now just put full reST directly in the documentation block of the devices (see [spike_detector.h](https://github.com/jougs/nest-simulator/blob/nestio/models/spike_detector.h#L39) for an example).

We could do the same for NESTML documentation and have reST-like *magic keywords* like the following, which could be replaced by the corresponding elements from the NESTML description by the NESTML tooling.
```
.. equations
.. parameter_table
.. references
```

Probably we also need some more discussion on this before jumping onto the implementation.

**Comment by clinssen** [comment]
Closing this issue as we currently have a working system in place, and there no clear advantages to making changes.
