### ISSUE TITLE
Generate API documentation for PyNESTML

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#514]
As part of the NESTML documentation, there should be an HTML render of the API (in the style of [docs.python.org](https://docs.python.org)). The set of HTML pages should be uploaded and linked somewhere (e.g. in the `doc` folder or under github-pages). Ideally, whenever a push or merge is made with respect to master, the documentation should be re-generated.

**Comment by Silmathoron** [comment]
@clinssen I think the solution is called readthedocs ^^
I can setup a config file in a few weeks if you want ;) you should also check with Jessica for the NEST Initiative RtD account: I think it would make sense to have it there.

**Comment by clinssen** [comment]
This has been in place for a long time now (see https://nestml.readthedocs.io/en/latest/pynestml.html).
