### ISSUE TITLE
Analyzing shapes taking too long + Handing delta function and state variables' boundaries.

### ISSUE THREAD

**Issue by dionperd** [nest/nestml#519]
Dear colleagues, NEST developers,

I hope I am addressing the questions below to the correct place.

I am trying to model in NEST the spiking model of Deco, Ponce-Alvarez et al. 2014, The Journal of Neuroscience.

Building the model with NESTML however gets stuck for too long (more than 24 hours) until I interrupt it, at the point of "Analyzing shapes...":

> (base) DionPerdChariteMBP:~ dionperd$ nestml --input_path /Users/dionperd/Software/Science/TVB/tvb-multiscale/tvb_nest/simulator_nest/models/nestml/iaf_cond_deco2014.nestml --target_path /Users/dionperd/Software/Science/TVB/tvb-multiscale/tvb_nest/simulator_nest/models/iaf_cond_deco2014_module --module_name iaf_cond_deco2014_module --logging_level INFO --store_log --dev
> [1,GLOBAL, INFO]: Start processing '/Users/dionperd/Software/Science/TVB/tvb-multiscale/tvb_nest/simulator_nest/models/nestml/iaf_cond_deco2014.nestml'!
> [2,iaf_cond_deco2014, INFO, [44:0;148:0]]: Start building symbol table!
> [3,iaf_cond_deco2014, INFO]: New type registered '1 / ms'!
> [4,iaf_cond_deco2014, WARNING, [70:20;70:34]]: Implicit casting from (compatible) type '1 / ms' to 'real buffer'.
> [5,iaf_cond_deco2014, WARNING, [71:20;71:34]]: Implicit casting from (compatible) type '1 / ms' to 'real buffer'.
> [6,iaf_cond_deco2014, WARNING, [72:16;72:26]]: Implicit casting from (compatible) type '1 / ms' to 'real buffer'.
> [7,iaf_cond_deco2014, WARNING, [73:16;73:26]]: Non-matching unit types at 1 / ms +/- kHz! Implicitly replaced by 1 / ms +/- 1.0 * kHz.
> [8,iaf_cond_deco2014, WARNING, [74:16;74:26]]: Implicit casting from (compatible) type '1 / ms' to 'real buffer'.
> [9,iaf_cond_deco2014, INFO]: New type registered 'mV / s'!
> [10,iaf_cond_deco2014, WARNING, [76:14;76:69]]: Non-matching unit types at pA +/- pA buffer! Implicitly replaced by pA +/- 1.0 * pA buffer.
> [11,iaf_cond_deco2014, INFO]: New type registered 'pA / nF'!
> [12,iaf_cond_deco2014, INFO, [51:22;51:22]]: Implicit casting from (compatible) type 'integer' to 'real'.
> [13,iaf_cond_deco2014, INFO, [52:22;52:22]]: Implicit casting from (compatible) type 'integer' to 'real'.
> [14,iaf_cond_deco2014, INFO, [53:18;53:18]]: Implicit casting from (compatible) type 'integer' to 'real'.
> [15,iaf_cond_deco2014, INFO, [54:18;54:18]]: Implicit casting from (compatible) type 'integer' to 'real'.
> [16,iaf_cond_deco2014, INFO, [55:18;55:18]]: Implicit casting from (compatible) type 'integer' to 'real'.
> [17,iaf_cond_deco2014, INFO, [51:4;51:22]]: Ode of 's_AMPA_ext' updated!
> [18,iaf_cond_deco2014, INFO, [52:4;52:22]]: Ode of 's_AMPA_rec' updated!
> [19,iaf_cond_deco2014, INFO, [53:4;53:18]]: Ode of 'x_NMDA' updated!
> [20,iaf_cond_deco2014, INFO, [54:4;54:18]]: Ode of 's_NMDA' updated!
> [21,iaf_cond_deco2014, INFO, [55:4;55:18]]: Ode of 's_GABA' updated!
> [22,iaf_cond_deco2014, INFO, [56:4;56:13]]: Ode of 'V_m' updated!
> [23,GLOBAL, INFO]: Analysing/transforming neuron 'iaf_cond_deco2014'
> [24,iaf_cond_deco2014, INFO, [44:0;148:0]]: Starts processing of the neuron 'iaf_cond_deco2014'
> [25,iaf_cond_deco2014, INFO, [44:0;148:0]]: The neuron 'iaf_cond_deco2014' will be solved numerically with GSL solver without modification!
> Validating input...
> Analyzing shapes...

Depending on when I interrupt it, it stops at different lines.

Building one of your models worked fine and fast. So, it must be a problem of my model code.

Please find my model code here:(https://www.dropbox.com/s/hi9n3bupa5nl1je/iaf_cond_deco2014.nestml?dl=0)

Besides, you will see commented in the code two functions that are trying to handle two additional issues:

a. the one that is known to you with the delta function #492 . 

b. the fact that my synaptic gating variables s_(AMPA/NMDA/GABA) express percentages of open channels and need to be bounded in the interval [0, 1]. I was getting errors when using the bounding function you will see commented. 

Before getting into details for these issues/errors, maybe you have a suggestion about how to handle the delta function and the state variable boundaries.

Thank you very much in advance.

Best regards,
Dionysios Perdikis, 
Brain Simulation Section, Charite, Berlin

**Comment by dionperd** [comment]
Dear colleagues,

Finally, I got it to build my model, following the example of iaf_cond_beta.nestml.

Please find the whole module code here:
(https://www.dropbox.com/sh/i6ma6so7fkaw2zx/AADw8Hct34_7QFtRw64R3_Gba?dl=0)

I only know have a couple of questions just for a deeper understanding of NESTML.

a. Do I understand correctly that I cannot use a user-defined function inside the equations block?
I have tried to define a bound function and use it to bound my state variables inside the differential equations and I am getting the following error:

> (base) DionPerdChariteMBP:~ dionperd$ nestml --input_path /Users/dionperd/Software/Science/TVB/tvb-multiscale/tvb_nest/simulator_nest/models/nestml/iaf_cond_deco2014.nestml --target_path /Users/dionperd/Software/Science/TVB/tvb-multiscale/tvb_nest/simulator_nest/models/iaf_cond_deco2014_module --module_name iaf_cond_deco2014_module --logging_level INFO --store_log --dev
> [1,GLOBAL, INFO]: Start processing '/Users/dionperd/Software/Science/TVB/tvb-multiscale/tvb_nest/simulator_nest/models/nestml/iaf_cond_deco2014.nestml'!
> [2,GLOBAL, INFO]: New type registered 'nS / ms'!
> [3,iaf_cond_deco2014, INFO, [44:0;138:0]]: Start building symbol table!
> [4,iaf_cond_deco2014, WARNING, [135:11;135:17]]: SPL_COMPARISON_OPERATOR_VISITOR : Operands of a logical rhs not compatible.([135:11;135:17])
> [5,iaf_cond_deco2014, WARNING, [135:32;135:38]]: SPL_COMPARISON_OPERATOR_VISITOR : Operands of a logical rhs not compatible.([135:32;135:38])
> [6,iaf_cond_deco2014, ERROR, [135:11;135:41]]: SPL_CONDITION_VISITOR : Mismatched conditional alternatives <pynestml.symbols.unit_type_symbol.UnitTypeSymbol object at 0x7fd2a0205dd0> and <pynestml.symbols.boolean_type_symbol.BooleanTypeSymbol object at 0x7fd2a0205910>-> Assuming real.([135:11;135:41])
> [7,iaf_cond_deco2014, ERROR, [135:11;135:53]]: SPL_CONDITION_VISITOR : The ternary operator condition must be boolean.([135:11;135:53])
> [8,iaf_cond_deco2014, ERROR, [135:4;135:53]]: Type of 'bound' could not be derived!
> [9,iaf_cond_deco2014, ERROR, [73:73;73:120]]: First argument of 'convolve' not a shape or equation!
> [10,iaf_cond_deco2014, ERROR, [74:73;74:120]]: First argument of 'convolve' not a shape or equation!
> [11,iaf_cond_deco2014, ERROR, [75:65;75:104]]: First argument of 'convolve' not a shape or equation!
> [12,iaf_cond_deco2014, ERROR, [76:65;76:104]]: First argument of 'convolve' not a shape or equation!
> [13,iaf_cond_deco2014, INFO]: New type registered 'nS / s'!
> [14,iaf_cond_deco2014, INFO]: New type registered 'nS / (ms s)'!
> [15,iaf_cond_deco2014, INFO]: New type registered 'nS / ms2'!
> [16,iaf_cond_deco2014, WARNING, [69:73;69:73]]: Implicit casting from (compatible) type 'nS' to 'integer'.
> [17,iaf_cond_deco2014, INFO]: New type registered 'nS2 / ms'!
> [18,iaf_cond_deco2014, WARNING, [69:16;69:34]]: Non-matching unit types at nS / ms +/- nS2 / ms! Implicitly replaced by nS / ms +/- 1e-09 * nS2 / ms.
> [19,iaf_cond_deco2014, INFO]: New type registered 'mV / s'!
> [20,iaf_cond_deco2014, WARNING, [78:14;78:113]]: Non-matching unit types at pA +/- pA buffer! Implicitly replaced by pA +/- 1.0 * pA buffer.
> [21,iaf_cond_deco2014, INFO]: New type registered 'pA / nF'!
> [22,iaf_cond_deco2014, INFO, [128:18;128:18]]: Implicit casting from (compatible) type 'nS buffer' to 'nS'.
> [23,iaf_cond_deco2014, INFO, [129:18;129:18]]: Implicit casting from (compatible) type 'nS buffer' to 'nS'.
> [24,iaf_cond_deco2014, INFO, [131:14;131:14]]: Implicit casting from (compatible) type 'nS buffer' to 'nS'.
> [25,iaf_cond_deco2014, INFO, [51:4;51:23]]: Ode of 's_AMPA_ext' updated!
> [26,iaf_cond_deco2014, INFO, [52:4;52:23]]: Ode of 's_AMPA_rec' updated!
> [27,iaf_cond_deco2014, INFO, [54:4;54:25]]: Ode of 'x_NMDA' updated!
> [28,iaf_cond_deco2014, INFO, [53:4;53:19]]: Ode of 's_NMDA' updated!
> [29,iaf_cond_deco2014, INFO, [55:4;55:19]]: Ode of 's_GABA' updated!
> [30,iaf_cond_deco2014, INFO, [56:4;56:13]]: Ode of 'V_m' updated!
> [31,GLOBAL, INFO]: Analysing/transforming neuron 'iaf_cond_deco2014'
> [32,iaf_cond_deco2014, INFO, [44:0;138:0]]: Starts processing of the neuron 'iaf_cond_deco2014'
> [33,iaf_cond_deco2014, INFO, [44:0;138:0]]: The neuron 'iaf_cond_deco2014' will be solved numerically with GSL solver without modification!
> [34,iaf_cond_deco2014, INFO, [44:0;138:0]]: Start building symbol table!
> [35,iaf_cond_deco2014, ERROR, [135:4;135:53]]: Type of 'bound' could not be derived!
> [36,iaf_cond_deco2014, INFO, [128:18;128:18]]: Implicit casting from (compatible) type 'nS buffer' to 'nS'.
> [37,iaf_cond_deco2014, INFO, [129:18;129:18]]: Implicit casting from (compatible) type 'nS buffer' to 'nS'.
> [38,iaf_cond_deco2014, INFO, [131:14;131:14]]: Implicit casting from (compatible) type 'nS buffer' to 'nS'.
> [39,iaf_cond_deco2014, INFO, [51:4;51:23]]: Ode of 's_AMPA_ext' updated!
> [40,iaf_cond_deco2014, INFO, [52:4;52:23]]: Ode of 's_AMPA_rec' updated!
> [41,iaf_cond_deco2014, INFO, [54:4;54:25]]: Ode of 'x_NMDA' updated!
> [42,iaf_cond_deco2014, INFO, [53:4;53:19]]: Ode of 's_NMDA' updated!
> [43,iaf_cond_deco2014, INFO, [55:4;55:19]]: Ode of 's_GABA' updated!
> [44,iaf_cond_deco2014, INFO, [56:4;56:13]]: Ode of 'V_m' updated!
> Traceback (most recent call last):
>   File "/Users/dionperd/.local/bin/nestml", line 11, in <module>
>     load_entry_point('NESTML==3.0.post0.dev0', 'console_scripts', 'nestml')()
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/frontend/pynestml_frontend.py", line 126, in main
>     return int(process())
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/frontend/pynestml_frontend.py", line 171, in process
>     _codeGenerator.generate_code(neurons)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/codegenerator.py", line 56, in generate_code
>     _codeGenerator.generate_code(neurons)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/nest_codegenerator.py", line 81, in generate_code
>     self.generate_neurons(neurons)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/codegenerator.py", line 42, in generate_neurons
>     self.generate_neuron_code(neuron)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/nest_codegenerator.py", line 174, in generate_neuron_code
>     self.generate_neuron_cpp_file(neuron)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/nest_codegenerator.py", line 195, in generate_neuron_cpp_file
>     neuron_cpp_file = self._template_neuron_cpp_file.render(self.setup_generation_helpers(neuron))
>   File "/Users/dionperd/anaconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "/Users/dionperd/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/Users/dionperd/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/dionperd/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/resources_nest/NeuronClass.jinja2", line 205, in top-level template code
>     {% include "directives/GSLDifferentiationFunction.jinja2" %}
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/resources_nest/directives/GSLDifferentiationFunction.jinja2", line 28, in top-level template code
>     f[{{names.array_index(odeVariable)}}] = {{printerGSL.print_expression(odeVariable.get_ode_definition(), prefix="node.")}};
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 67, in print_expression
>     return self.__do_print(node, prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 106, in __do_print
>     lhs = self.print_expression(node.get_lhs(), prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 67, in print_expression
>     return self.__do_print(node, prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 94, in __do_print
>     rhs = self.print_expression(node.get_expression(), prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 67, in print_expression
>     return self.__do_print(node, prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 98, in __do_print
>     return self.reference_converter.convert_encapsulated() % self.print_expression(node.get_expression(), prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 67, in print_expression
>     return self.__do_print(node, prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 89, in __do_print
>     return self.print_function_call(node.get_function_call(), prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/expressions_pretty_printer.py", line 135, in print_function_call
>     function_name = self.reference_converter.convert_function_call(function_call, prefix=prefix)
>   File "/Users/dionperd/.local/lib/python3.7/site-packages/NESTML-3.0.post0.dev0-py3.7.egg/pynestml/codegeneration/gsl_reference_converter.py", line 142, in convert_function_call
>     if function_name == PredefinedFunctions.LOG:
> AttributeError: type object 'PredefinedFunctions' has no attribute 'LOG'

b. I think I am getting the same .cpp code no matter if I omit the convolve() term in my differential equations. Do you agree that this is true in my case where I only need to add spikes to a differential integration without any convolution? If yes, why do the authors of iaf_cond_beta do not remove the convolution?

Thanks a lot.

Best,
D.P.

**Comment by Silmathoron** [comment]
Hi @dionperd sorry for the late reply.
It seems that the file is no longer available, could you please reupload it?
To check what might be problematic, we would also need to know precisely which version of NESTML and odetoolbox you are using.

Finally, could you provide more information on what was not working with the bounding function? (it works fine in my files)

**Comment by clinssen** [comment]
@dionperd : I am happy to report that the new version of ode-toolbox is now ready for beta testing. This is likely to help with the issue that you are experiencing.

To use the beta version of ode-toolbox, you have to clone the repository https://github.com/clinssen/ode-toolbox and checkout a particular branch: `merge_shape_ode_concepts-dev`.

To use the beta version of NESTML, you have to clone the repository https://github.com/clinssen/nestml and checkout a particular branch: `ode-toolbox-integration`.

You need both the beta version of NESTML and the beta version of ode-toolbox, they are strongly coupled. Once you have them both on your computer (and you made sure to set the PYTHONPATHs so it picks up on the beta versions, not the previous installation), simply run NESTML as you normally would.

Please let us know how you fare!

**Comment by oscr104** [comment]
@clinssen I have cloned the ode-toolbox branch version - Do I now need to install this into the conda environment I run nest from?

**Comment by clinssen** [comment]
I apologise for not being personally familiar with anaconda, but one thing to make sure is to set your PYTHONPATH environment variable so that Python finds the right library in the right place. In iPython, you can check the path by:
```
In [1]: import odetoolbox

In [2]: odetoolbox?
Type:        module
String form: <module 'odetoolbox' from '/home/archels/ode-toolbox/odetoolbox/__init__.py'>
File:        ~/ode-toolbox/odetoolbox/__init__.py
```

**Comment by clinssen** [comment]
@dionperd: we recently merged a lot of improvements related to processing of equations. Could you perhaps upload your model again (or paste in this thread) so that we can give it a check on the new version? Otherwise, could you please close the issue? Many thanks!

**Comment by dionperd** [comment]
Sure. I have moved away from using nestml. I am sorry for not being more responsive. Therefore, I am closing the issue.
