### ISSUE TITLE
Implementing gap junctions in HH type model - any experience?

### ISSUE THREAD

**Issue by oscr104** [nest/nestml#522]
Hi all,

Currently working on implementing a Hodgkin Huxley type model in NestML, mostly standard ionic currents & associated activation/inactivation variables, for which I can find examples implemented in the nestML models directory to base my own from.

One thing I can't see is any examples of nestML models with  gap junction functionality compatible with the NEST gap junction functions. Has anybody here had experience implementing gap junctions in nestML that they can share?

Thanks!

**Comment by clinssen** [comment]
I do not believe that gap junctions have been tested before, but it could be the case that adding language support for them is easy (e.g. adding a different port type). A good starting point would be to look at a NEST simulator model with and without gap junctions (e.g. `hh_psc_alpha` and `hh_psc_alpha_gap`) and, on the basis of the differences, make an inventory of what would be required.

**Comment by clinssen** [comment]
Some further discussion points on gap junction support in NESTML:

- it might be tricky to integrate this into the language itself; for now, use code generator options dict
- need to reference two variables there: V_m and I_gap
- generate code in the GSL time stepping function that references the variables
    - what if an analytic solver is used to integrate V_m? I_gap should also be available inside the ``update()`` function (where analytic integrator is called)
- generate new ``update_()`` function (with different signature)
- generate new helper functions (``wfr_update()``, and ``update()`` which just calls ``update_()`` internally)
- generate new ``handle( GapJunctionEvent& e )`` function
