### ISSUE TITLE
Issues compiling nestML code.

### ISSUE THREAD

**Issue by oscr104** [nest/nestml#523]
Hi all,

Coming to nestML with programming experience in python & MATLAB, but very very little C/C++ knowledge (only following by the numbers instructions to compile packages).

Currently I am trying to follow the instructions on the nestml docs page (https://github.com/nest/nestml/blob/master/doc/tutorial/Slides.pdf   slide 20 terminal commands) for compiling and installing a new nestML model into nest, but hitting an issue on the final compile stage

Here is the command that causes the problem:

    install_nest("/home/nd17878/comp/nest/nestML_models/builds", "/home/nd17878/anaconda3/pkgs/nest-simulator-2.18.0-nompi_py37hf650cc7_103")

and here is the error message:

    -- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:98 (project):
  The CMAKE_CXX_COMPILER:

    /home/conda/feedstock_root/build_artifacts/nest-simulator_1569564429644/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/nd17878/comp/nest/nestML_models/builds/CMakeFiles/CMakeOutput.log".
See also "/home/nd17878/comp/nest/nestML_models/builds/CMakeFiles/CMakeError.log".
PyNestML: Something went wrong in 'cmake', see error above!
abort installation...

I have made edits in the suggested places (added a CXX=<pathtocmakeexecytable> variable in the .sh script of the relevant conda environment I am running from, as well as the nestvars.sh script, and ditto in the CMakeCache text file, but no changes to the error messages above.

Can anybody tell me what I am getting wrong?

**Comment by clinssen** [comment]
The value for `CMAKE_CXX_COMPILER` is obtained from the output of `nest-config` at https://github.com/nest/nestml/blob/85cb3049ea452d15389653a58c0b708c778f04b1/pynestml/codegeneration/resources_nest/setup/CMakeLists.jinja2#L102 (see also the assignment on line 115). It could be that nest-config is returning faulty information; could you try running `nest-config` from the command line and posting the results?

**Comment by oscr104** [comment]
nest-config --compiler

in the terminal gives the same erroneous directory for a (non-existent) path to the compiler:

/home/conda/feedstock_root/build_artifacts/nest-simulator_1569564429644/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++

So in order to provide the correct path to the compiler, I should alter the CMakeLists file? 

Thanks for your help! :)

**Comment by clinssen** [comment]
The compiler returned by `nest-config` is set during the build of the NEST simulator itself; more precisely the CMake configuration stage. `nest-config` is actually a bash script; if you open it in your favourite text editor, you should be able to correct the entry under `--compiler`. I'm not sure why this obtains the wrong value for you; perhaps due to a temporary (non-persistent) build environment in conda? Manually fixing it is obviously only a hack, but might be the least painful method until we figure this one out completely.

**Comment by oscr104** [comment]
Update

Changing the nest-config script hasnt hasn't remedied the problem :(  

I tried deleting the conda environment and starting again from scratch, this time including cmake in the list of modules to install in the conda environment build. Following the same steps as above, I still encounter the same error.

The steps I used to create the conda environment with nest are as detailed on the NEST readthedocs page (https://nest-simulator.readthedocs.io/en/latest/installation/conda_install.html). There is a disclaimer that the conda version of NEST is still in beta mode, and so I think this might be involved in my issues.

I am considering starting from scratch again, using the standard Ubuntu installation process, as that includes cmake configuration steps

**Comment by clinssen** [comment]
@steffengraber : any ideas? Can we add a "pip install nestml" somewhere in our conda distribution? I am unfortunately not very familiar with Anaconda.

**Comment by steffengraber** [comment]
Hi, 

this is the first time that I have tried `nestml` with the `conda` installation with NEST. I have more or less followed the instructions under https://github.com/nest/nestml/blob/master/doc/tutorial/izhikevich_tutorial_workflow.rst.

In preparation I created a conda environment NEST and installed some additional dependencies: 

```
conda create --name wnestml
conda activate wnestml
conda install -c conda-forge nest-simulator ipython cxx-compiler pyqt wxpython
pip install nestml
```
I have tested everything with the `izhikevich_tutorial` in the nestml repository in doc/tutorial/ 

`git clone https://github.com/nest/nestml.git`

Tested the path to  c++

```
which c++ 
# '/home/graber/miniconda3/envs/wnestml/bin/c++'
```
Corrected the entry under --compiler with the output of `which c++` in `nest-config`

`nano /home/graber/miniconda3/envs/wnestml/bin/nest-config`

Now set the correct paths and started ipython

`PYTHONPATH=$PYTHONPATH:/home/graber/miniconda3/envs/wnestml/lib/python3.7/site-packages/ LD_LIBRARY_PATH=/tmp/nestml-component ipython`

In `ipython`:

```
from pynestml.frontend.pynestml_frontend import to_nest, install_nest
to_nest(input_path="/home/graber/work/nestml/doc/tutorial/izhikevich_solution.nestml", target_path="/tmp/nestml-component", logging_level="INFO")
install_nest("/tmp/nestml-component", "/home/graber/miniconda3/envs/wnestml/") 
```

After generating the code, tested with

```
import matplotlib
matplotlib.use('WXAgg')
import nest
import matplotlib.pyplot as plt

nest.set_verbosity("M_WARNING")
nest.ResetKernel()
nest.Install("nestmlmodule")

neuron = nest.Create("izhikevich_tutorial")
voltmeter = nest.Create("voltmeter")

nest.SetStatus(voltmeter, [{"withgid": True, "record_from" : [nest.GetStatus(neuron)[0]["recordables"][1]]}])
nest.Connect(voltmeter, neuron)

cgs = nest.Create('dc_generator')
nest.SetStatus(cgs, "amplitude", 25.)
nest.Connect(cgs, neuron)

nest.Simulate(250.)

plt.plot(nest.GetStatus(voltmeter)[0]["events"]["times"], nest.GetStatus(voltmeter)[0]["events"]["v"])
plt.show()
```

This works for me so far.
I hope this helps.

**Comment by oscr104** [comment]
Thank you so much! I think this has solved the compiler problem, which I think was resulting from both the bad entry in the nest-config script for --compiler, and also by my incorrect entry for the pythonpath (to a different version of python OUTSIDE of the nest environment).

The tutorial installation works. My code fails on the final stage, generating a seemingly infinite loop of the following code repeating

nestML_modelsmodule Configuration Summary
-------------------------------------------------------

C++ compiler         : /home/nd17878/anaconda3/envs/wnestml/bin/c++
Build static libs    : OFF
C++ compiler flags   : -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/nd17878/anaconda3/envs/wnestml/include 
NEST compiler flags  : -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/nd17878/anaconda3/envs/wnestml/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/nest-simulator_1574238638875/work=/usr/local/src/conda/nest-simulator-2.18.0 -fdebug-prefix-map=/home/nd17878/anaconda3/envs/wnestml=/usr/local/src/conda-prefix -std=c++11 -O2 -Wall -fdiagnostics-color=auto
NEST include dirs    :  -I/home/nd17878/anaconda3/envs/wnestml/include/nest -I/home/nd17878/anaconda3/envs/wnestml/include -I/home/nd17878/anaconda3/envs/wnestml/include -I/home/nd17878/anaconda3/envs/wnestml/include
NEST libraries flags : -L/home/nd17878/anaconda3/envs/wnestml/lib64 -lnestutil -lnest -lrandom -lsli -lnestkernel -ltopology  /home/nd17878/anaconda3/envs/wnestml/lib/libltdl.so /home/nd17878/anaconda3/envs/wnestml/lib/libreadline.so /home/nd17878/anaconda3/envs/wnestml/lib/libncurses.so /home/nd17878/anaconda3/envs/wnestml/lib/libgsl.so /home/nd17878/anaconda3/envs/wnestml/lib/libgslcblas.so

-------------------------------------------------------

You can now build and install 'nestML_modelsmodule' using
  make
  make install

The library file libnestML_modelsmodule.so will be installed to
  /home/nd17878/anaconda3/envs/wnestml/lib64/nest
Help files will be installed to
  /home/nd17878/anaconda3/envs/wnestml/share/doc/nest

The module can be loaded into NEST using
  (nestML_modelsmodule) Install       (in SLI)
  nest.Install(nestML_modelsmodule)   (in PyNEST)

-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/cmake

-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /home/nd17878/anaconda3/envs/wnestml/bin/c++
-- Check for working CXX compiler: /home/nd17878/anaconda3/envs/wnestml/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

**Comment by oscr104** [comment]
Hi Steffen

Thanks so much for your step-by-step process - the above code works perfectly with the Izhikevich tutorial. My own nestML model is still a little ways from being functional, but now I can tell that this is due to some errors in the nestml script itself, rather than failing to compile it properly.

**Comment by steffengraber** [comment]
Hi @oscr104 

Thanks for the notice. I hope you can solve the problems.

**Comment by steffengraber** [comment]
@clinssen 

You can close the issue
