### ISSUE TITLE
Maximum recursion warning when trying to compile nestML model

### ISSUE THREAD

**Issue by oscr104** [nest/nestml#527]
I am trying to write a Hodgkin Huxley formalism model for a single unit, based on the hh_psc_alpha nestML code, with some added currents and a term for calcium concentration. 

The model will start compiling with no 'ERROR' messages, just some WARNING messages mostly regarding unit conversions. However then the process will stop and a series of python error messages will appear under the heading 'RecursionError'.

I'm not that experienced at all with compiling, or with nestML, however I think this may be a problem either with the formalism of my equations in nestML, or with the units necessary for the Calcium concentration term....

Full model code and error message is below:

**Comment by oscr104** [comment]
"""
Name: hh_lc_alpha - Hodgkin Huxley neuron model.



Description:

  Edited by OD 16/12/19 - addition of currents (I_p, I_ahp I_Ca) and calcium conc terms, plus alterations to ODEs to reflect Alvarez & al 2002 LC hh model

based on:  hh_psc_alpha is an implementation of a spiking neuron using the Hodkin-Huxley
 formalism.
"""
neuron hh_lc_alpha:
  state:
    r integer # number of steps in the current refractory phase
    #V_m   # somatic Voltages
    #V_d # dendritic voltage
    #Ca_conc  # [Ca]  umol/kg
  end

  initial_values:
    V_m mV = -65. mV # Membrane potential
    V_d mV = -67. mV # dendritic potential
    function alpha_n_init real = 0.01*(V_m/mV + 34. ) / ( 1. - exp( - .2 * (V_m / mV + 34. ) ) )
    function beta_n_init real = 0.125 * exp( -(V_m / mV + 40. ) / 80.)
    function alpha_m_init real = 0.1 * ( V_m / mV + 25. ) / ( 1.- exp( -0.1 * ( V_m / mV +25.)))
    function beta_m_init real = 4. * exp( -( V_m / mV + 50.) / 18.)
    function alpha_h_init real = 0.07 * exp( -( V_m / mV + 40. ) / 20. )
    function beta_h_init real = 1. / ( 1. + exp(-0.1 * ( V_m / mV + 14.)))
      # Formulae for p variables (slow Na current)
    function alpha_p_init real = 0.0001 * ( V_m / mV + 30.) / ( 1 - exp( -0.05 * ( V_m / mV + 40.)))
    function beta_p_init real = 0.004 * exp( -( V_m / mV + 60. ) / 18.)

    Act_m real =  alpha_m_init / ( alpha_m_init + beta_m_init )   # Activation variable m for Na
    Inact_h real = alpha_h_init / ( alpha_h_init + beta_h_init )    # Inactivation variable h for Na
    Act_n real =  alpha_n_init / ( alpha_n_init + beta_n_init ) # Activation variable n for K
    Act_p real = alpha_p_init / ( alpha_p_init + beta_p_init )   # Activation for Slow Na current

    #Act_mca real = 0.25
    Inact_yca real = 0.128 #lc_vals_alt
    Ca_conc umol/kg = 5 umol/kg

  end

  equations:
    # synapses: alpha functions
    shape I_syn_in = (e/tau_syn_in) * t * exp(-t/tau_syn_in)
    shape I_syn_ex = (e/tau_syn_ex) * t * exp(-t/tau_syn_ex)

    function I_syn_exc pA = convolve(I_syn_ex, spikeExc)
    function I_syn_inh pA = convolve(I_syn_in, spikeInh)

    #Ca dynamics variables (non ODE)
    function Act_mca real = 1. / ( 1. + exp( -(V_m / mV + 55.) / 9.))#Formulae for Ca current variables
    function y_inf real = 1. / ( 1. + exp(( V_m / mV + 77. ) / 5. ))
    function tau_y real = 20. + 100. / ( 1. + exp(( V_m / mV + 76. ) / 3. ))

    function I_Na pA = g_Na * Act_m * Act_m * Act_m * Inact_h * ( V_m - E_Na)   #Alvarez
    function I_K pA = g_K * Act_n * Act_n * Act_n * Act_n * ( V_m - E_K)  # alvarez
    function I_L pA = g_L * ( V_m - E_L)
    function I_P pA =  g_P * Act_p * Act_p * ( V_m - E_Na) #alvarez
    function I_Ca pA = g_Ca * Act_mca * Act_mca * Inact_yca * ( V_m - E_Ca )  #alvarez
    function I_ahp pA = g_ahp * ( Ca_conc / ( Ca_conc + 1. )) * ( V_m - E_K)  #alvarez UNITS ?

    V_m' =( -( I_Na + I_K + I_L + I_P + I_Ca + I_ahp ) + currents + I_e + I_syn_inh + I_syn_exc ) / C_m
    #V_d' = ( g_Ld * ( V_d - E_Ld ) - g_d * ( V_d - V_m) ) / C_m


    # Act_n
    function alpha_n real = 0.01*(V_m/mV + 34. ) / ( 1. - exp( - .2 * (V_m / mV + 34. ) ) )
    function beta_n real = 0.125 * exp( -(V_m / mV + 40. ) / 80.) # Alvarez
    Act_n' = ( 3 * (alpha_n * ( 1 - Act_n ) - beta_n * Act_n )) / ms #adapt from Alvarez

    # Act_m
    function alpha_m real = 0.1 * ( V_m / mV + 25. ) / ( 1.- exp( -0.1 * ( V_m / mV +25.))) #alvarez
    function beta_m real = 4. * exp( -( V_m / mV + 50.) / 18.)  # alvarez
    Act_m' = ( alpha_m * ( 1 - Act_m ) - beta_m * Act_m ) / ms # same as MNa -variable  OR try as function using init value equation?

    # Inact_h'
    function alpha_h real = 0.07 * exp( -( V_m / mV + 40. ) / 20. )   # alvarez
    function beta_h real = 1. / ( 1. + exp( -0.1 * ( V_m / mV + 14.)))            # alvarez
    Inact_h' = (3. * ( alpha_h * (1. - Inact_h) - beta_h * Inact_h)) / ms

    #Act_p'
    function alpha_p real = 0.0001 * ( V_m / mV + 30.) / ( 1 - exp( -0.05 * ( V_m / mV + 40.)))
    function beta_p real = 0.004 * exp( -( V_m / mV + 60. ) / 18.)
    Act_p' = (alpha_p * ( 1. - Act_p) - beta_p * Act_p) / ms

    #[Ca]
    Ca_conc' = (-0.002 * 2. * ( V_m / mV -  E_Ca / mV) / ( 1. + exp ( -( V_m / mV + 25. ) / 2.5 )) - Ca_conc / 80. ) /ms   #units error...
    Inact_yca' = (0.75 * (y_inf - Inact_yca)/tau_y) /ms


  end

  parameters:
    t_ref ms = 2.0 ms      # Refractory period
    g_Na nS = 12000.0 nS    # Sodium peak conductance
    g_K nS = 3600.0 nS      # Potassium peak conductance
    g_L nS = 30. nS          # Leak conductance
    g_Ld nS = 1. nS          # Dendritic leak
    g_P nS = 100. nS
    g_ahp nS = 50. nS
    g_Ca nS = 100. nS
    g_d nS = 30. bS
    C_m pF = 100.0 pF       # Membrane Capacitance
    E_Na mV = 40. mV         # Sodium reversal potential
    E_K mV = -110. mV        # Potassium reversal potentia
    E_L mV = -65. mV     # Leak reversal Potential (aka resting potential)
    E_Ld mV = -67. mV
    E_Ca mV = 140. mV
    tau_syn_ex ms = 0.2 ms  # Rise time of the excitatory synaptic alpha function i
    tau_syn_in ms = 50.0 ms  # Rise time of the inhibitory synaptic alpha function
    I_e pA = 0 pA           # Constant Current
  end

  internals:
    RefractoryCounts integer = steps(t_ref) # refractory time in steps
  end

  input:
      spikeInh pA <- inhibitory spike
      spikeExc pA <- excitatory spike
      currents <- current
  end

  output: spike

  update:
    U_old mV = V_m
    integrate_odes()
    # sending spikes: crossing 0 mV, pseudo-refractoriness and local maximum...
    if r > 0: # is refractory?
      r -= 1
    elif V_m > 0 mV and U_old > V_m: # threshold && maximum
      r = RefractoryCounts
      emit_spike()
    end

  end

end

**Comment by oscr104** [comment]
error message resulting from "to_nest(input_path="/home/nd17878/nestml/models/hh_lc_alpha.nestml", target_path="/home/nd17878/lc_code_git/nestML_models/hh_lc_alpha", logging_level="INFO", module_name="hh_lc_module")


[1,hh_lc_alpha, INFO]: Start processing '/home/nd17878/nestml/models/hh_lc_alpha.nestml'!
[2,hh_lc_alpha, INFO]: New type registered 'umol / kg'!
[3,hh_lc_alpha, INFO, [52:0;181:0]]: Start building symbol table!
[4,hh_lc_alpha, INFO]: New type registered 'mV / s'!
[5,hh_lc_alpha, WARNING, [104:12;104:53]]: Non-matching unit types at pA +/- pA buffer! Implicitly replaced by pA +/- 1.0 * pA buffer.
[6,hh_lc_alpha, INFO]: New type registered 'pA / pF'!
[7,hh_lc_alpha, INFO]: New type registered '1 / ms'!
[8,hh_lc_alpha, INFO]: New type registered 'umol / (kg s)'!
[9,hh_lc_alpha, WARNING, [129:16;129:97]]: Implicit casting from (compatible) type 'umol / kg' to 'real'.
[10,hh_lc_alpha, INFO]: New type registered 'umol / (kg ms)'!
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-16-0e44bd65d138> in <module>
----> 1 to_nest(input_path="/home/nd17878/nestml/models/hh_lc_alpha.nestml", target_path="/home/nd17878/lc_code_git/nestML_models/hh_lc_alpha", logging_level="INFO", module_name="hh_lc_module")

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/frontend/pynestml_frontend.py in to_nest(input_path, target_path, logging_level, module_name, store_log, suffix, dev)
     89 
     90     FrontendConfiguration.parse_config(args)
---> 91     if not process() == 0:
     92         raise Exception("Error(s) occurred while processing the model")
     93 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/frontend/pynestml_frontend.py in process()
    147         nestml_files = [nestml_files]
    148     for nestml_file in nestml_files:
--> 149         parsed_unit = ModelParser.parse_model(nestml_file)
    150         if parsed_unit is not None:
    151             compilation_units.append(parsed_unit)

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/utils/model_parser.py in parse_model(cls, file_path)
    159         Logger.set_log(log_to_restore, counter)
    160         for neuron in ast.get_neuron_list():
--> 161             neuron.accept(ASTSymbolTableVisitor())
    162             SymbolTable.add_neuron_scope(neuron.get_name(), neuron.get_scope())
    163         return ast

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_node.py in accept(self, visitor)
    182         :type visitor: Inherited from ASTVisitor.
    183         """
--> 184         visitor.handle(self)
    185 
    186     def __str__(self):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in handle(self, _node)
    704         self.get_real_self().visit(_node)
    705         self.get_real_self().traverse(_node)
--> 706         self.get_real_self().endvisit(_node)
    707         return
    708 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in endvisit(self, node)
   1036             return
   1037         if isinstance(node, ASTNeuron):
-> 1038             self.endvisit_neuron(node)
   1039             return
   1040         if isinstance(node, ASTOdeEquation):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_symbol_table_visitor.py in endvisit_neuron(self, node)
     79     def endvisit_neuron(self, node):
     80         # before following checks occur, we need to ensure several simple properties
---> 81         CoCosManager.post_symbol_table_builder_checks(node, after_ast_rewrite=self.after_ast_rewrite_)
     82         # the following part is done in order to mark conductance based buffers as such.
     83         if node.get_input_blocks() is not None and node.get_equations_blocks() is not None and \

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/cocos/co_cos_manager.py in post_symbol_table_builder_checks(cls, neuron, after_ast_rewrite)
    348         cls.check_vector_in_non_vector_declaration_detected(neuron)
    349         cls.check_sum_has_correct_parameter(neuron)
--> 350         cls.check_expression_correct(neuron)
    351         cls.check_function_argument_template_types_consistent(neuron)
    352         return

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/cocos/co_cos_manager.py in check_expression_correct(cls, neuron)
    294         :type neuron: ast_neuron
    295         """
--> 296         CoCoIllegalExpression.check_co_co(neuron)
    297 
    298     @classmethod

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/cocos/co_co_illegal_expression.py in check_co_co(cls, neuron)
     43         :type neuron: ASTNeuron
     44         """
---> 45         neuron.accept(CorrectExpressionVisitor())
     46 
     47 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_node.py in accept(self, visitor)
    182         :type visitor: Inherited from ASTVisitor.
    183         """
--> 184         visitor.handle(self)
    185 
    186     def __str__(self):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in handle(self, _node)
    703     def handle(self, _node):
    704         self.get_real_self().visit(_node)
--> 705         self.get_real_self().traverse(_node)
    706         self.get_real_self().endvisit(_node)
    707         return

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in traverse(self, node)
    911             return
    912         if isinstance(node, ASTNeuron):
--> 913             self.traverse_neuron(node)
    914             return
    915         if isinstance(node, ASTOdeEquation):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in traverse_neuron(self, node)
   1246     def traverse_neuron(self, node):
   1247         if node.get_body() is not None:
-> 1248             node.get_body().accept(self.get_real_self())
   1249         return
   1250 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_node.py in accept(self, visitor)
    182         :type visitor: Inherited from ASTVisitor.
    183         """
--> 184         visitor.handle(self)
    185 
    186     def __str__(self):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in handle(self, _node)
    703     def handle(self, _node):
    704         self.get_real_self().visit(_node)
--> 705         self.get_real_self().traverse(_node)
    706         self.get_real_self().endvisit(_node)
    707         return

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in traverse(self, node)
    854             return
    855         if isinstance(node, ASTBody):
--> 856             self.traverse_body(node)
    857             return
    858         if isinstance(node, ASTComparisonOperator):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in traverse_body(self, node)
   1110         if node.get_body_elements() is not None:
   1111             for sub_node in node.get_body_elements():
-> 1112                 sub_node.accept(self.get_real_self())
   1113         return
   1114 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_node.py in accept(self, visitor)
    182         :type visitor: Inherited from ASTVisitor.
    183         """
--> 184         visitor.handle(self)
    185 
    186     def __str__(self):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in handle(self, _node)
    703     def handle(self, _node):
    704         self.get_real_self().visit(_node)
--> 705         self.get_real_self().traverse(_node)
    706         self.get_real_self().endvisit(_node)
    707         return

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in traverse(self, node)
    851             return
    852         if isinstance(node, ASTBlockWithVariables):
--> 853             self.traverse_block_with_variables(node)
    854             return
    855         if isinstance(node, ASTBody):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in traverse_block_with_variables(self, _node)
   1104         if _node.get_declarations() is not None:
   1105             for sub_node in _node.get_declarations():
-> 1106                 sub_node.accept(self.get_real_self())
   1107         return
   1108 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_node.py in accept(self, visitor)
    182         :type visitor: Inherited from ASTVisitor.
    183         """
--> 184         visitor.handle(self)
    185 
    186     def __str__(self):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in handle(self, _node)
    702 
    703     def handle(self, _node):
--> 704         self.get_real_self().visit(_node)
    705         self.get_real_self().traverse(_node)
    706         self.get_real_self().endvisit(_node)

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in visit(self, node)
    741             return
    742         if isinstance(node, ASTDeclaration):
--> 743             self.visit_declaration(node)
    744             return
    745         if isinstance(node, ASTElifClause):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/cocos/co_co_illegal_expression.py in visit_declaration(self, node)
     63                 return
     64             lhs_type = node.get_data_type().get_type_symbol()
---> 65             rhs_type = node.get_expression().type
     66             if isinstance(rhs_type, ErrorTypeSymbol):
     67                 LoggingHelper.drop_missing_type_error(node)

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_expression_node.py in type(self)
     40         from pynestml.visitors.ast_expression_type_visitor import ASTExpressionTypeVisitor
     41         if self.__type is None:
---> 42             self.accept(ASTExpressionTypeVisitor())
     43         return copy(self.__type)
     44 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_node.py in accept(self, visitor)
    182         :type visitor: Inherited from ASTVisitor.
    183         """
--> 184         visitor.handle(self)
    185 
    186     def __str__(self):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_expression_type_visitor.py in handle(self, _node)
     72         """
     73         self.traverse(_node)
---> 74         self.get_real_self().visit(_node)
     75         self.get_real_self().endvisit(_node)
     76 

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_visitor.py in visit(self, node)
    807             return
    808         if isinstance(node, ASTSimpleExpression):
--> 809             self.visit_simple_expression(node)
    810             return
    811         if isinstance(node, ASTSmallStmt):

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/visitors/ast_numeric_literal_visitor.py in visit_simple_expression(self, node)
     50             else:
     51                 node.type = scope.resolve_to_symbol(var_name, SymbolKind.TYPE)
---> 52             node.type.referenced_object = node
     53             return
     54 

... last 5 frames repeated, from the frame below ...

~/anaconda3/envs/lc_nest/lib/python3.8/site-packages/pynestml/meta_model/ast_expression_node.py in type(self)
     40         from pynestml.visitors.ast_expression_type_visitor import ASTExpressionTypeVisitor
     41         if self.__type is None:
---> 42             self.accept(ASTExpressionTypeVisitor())
     43         return copy(self.__type)
     44 

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by clinssen** [comment]
You have a typo in your model specification: ` g_d nS = 30. bS` should read `nS`.

However, even with a faulty unit, this should certainly not throw a RecursionError! Thanks for reporting this, I will make sure a friendly error message is shown instead. Related commits will be pushed to the ode-toolbox-integration branch (#515).

**Comment by clinssen** [comment]
This is now fixed by https://github.com/nest/nestml/pull/515/commits/a9ce67c1b8175752bf1e2eb377f034cfcaf25f46.
