### ISSUE TITLE
implementation of synapse with 2 variables (Gradual Rise)

### ISSUE THREAD

**Issue by Ziaeemehr** [nest/nestml#532]
I'm almost new to nestml, so be patient please!

In "An Introduction to modeling neural dynamics" by Borgers, section 20.2, the synaptic current is defined as:
```
I_syn = g_bar_syn * s(t) (V_rev - V_post)
dq/dt = (1+tanh(V/10)) / 2 * (1-q) / tau_rise - q / 0.1 - q / tau_decay_q
ds / dt = q (1 - s) / tau_rise - s / tau_decay
```
![fig_20_4](https://user-images.githubusercontent.com/7780103/72665012-b4322500-3a19-11ea-9485-dfa425cc7da3.png)

The question is how to implement this synapse?
I searched for a while in previous  issues, nothing matched to this.
Thank you in advance for any guide.

**Comment by Ziaeemehr** [comment]
Is it possible to define an ODE for synapse variable? I think the problem is sigmoid function (`F(V_pre)`) the depends on `V_pre` of the presynaptic neuron which we do not have access to it.
for the simple case of one variable:
```python
I_syn = g_bar_syn * s(t) (V_rev - V_post)
ds/dt = F(v_pre)(1-s) / tau_rise - s / tau_decay
```
is implemented as :
```python
shape g_ex = exp(-1/tau_syn_ex*t)
function I_syn_exc pA = convolve(g_ex, spikeExc) * ( V_m - E_ex )
```
and instead of sigmoid function we use the condition on voltage `V_m` passing the threshold. 

for the case of 2 variable synapse, if we have a spike at `t=0`, then approximately `s` satisfy [Borgers eq. 20.11]
```python
ds/dt = exp(-t / tau_decay_q) * (1 - s) / tau_rise - s / tau_decay
```
the term `exp(-t / tau_decay_q) * (1 - s) / tau_rise` initially drives `s` up. 
However, as `exp(-t / tau_decay_q)`, decays, the term `-s / tau_decay` takes over.

**Comment by clinssen** [comment]
Dear @Ziaeemehr: I'm afraid that in NEST Simulator, it is proving extremely difficult to obtain access to the presynaptic membrane potential. Aside from that, the synapse could be expressed in NESTML (beta version!) So, if you would like to simulate your model in NEST, we need to ask the core NEST Simulator developers for support. Could I ask you to open an issue on nest/nest-simulator, and explain your problem (accessing presynaptic membrane potential--at what times, etc.) and use case?

**Comment by Ziaeemehr** [comment]
Thank you @clinssen . I open the issue in nest simulator.
Just for nlow I  tried to implement AMPA receptor to my HH like model.
I followed the `hill_tononi.nestml`, and it worked properly.
to connect two neuron I used:
```python
nest.Connect(neuron1, neuron2)
```
![ampa_coupled](https://user-images.githubusercontent.com/7780103/73002279-052a8a80-3e19-11ea-9df6-3dd8da368d66.png)

upper panel show the voltage recorded from postsynaptic neuron.
the middle panel is the synaptic current from AMPA receptor and the lower panel show the spikes of presynaptic neuron.

So far, so good. but I can not print the receptor types:
```
File "example_traub_ampa_single_neuron.py", line 28, in <module>
    receptors = nest.GetDefaults(model)["receptor_types"]
KeyError: 'receptor_types'
```

When I add the code for NMDA receptor to nestml file, 

```python
receptors = nest.GetDefaults(model)["receptor_types"]
```
command give me the receptors:
```python
{'AMPA': 1, 'NMDA': 2}
```
but when I try to connect the two neurons, 
```python
nest.Connect(neuron1, neuron2, syn_spec={"receptor_types": "NMDA"})
```
```{r, engine='bash'}
Traceback (most recent call last):
  File "example_traub_ampa_coupled_neuron.py", line 43, in <module>
    nest.Connect(neuron1, neuron2, syn_spec={"receptor_type": "NMDA"})
  File "/home/abolfazl/prog/install-dir/nest-simulator-2.18.0_build/lib/python3.6/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/abolfazl/prog/install-dir/nest-simulator-2.18.0_build/lib/python3.6/site-packages/nest/lib/hl_api_connections.py", line 362, in Connect
    sr('Connect')
  File "/home/abolfazl/prog/install-dir/nest-simulator-2.18.0_build/lib/python3.6/site-packages/nest/ll_api.py", line 132, in catching_sli_run
    raise exceptionCls(commandname, message)
nest.ll_api.BadProperty: ('BadProperty in Connect_g_g_D_D: Cannot handle parameter type. Received stringtype', 'BadProperty', <SLILiteral: Connect_g_g_D_D>, ': Cannot handle parameter type. Received stringtype')
```
I don't know where is the problem. Am I doing some thing wrong?
Could you please give me some help. @clinssen.

[traub_ampa_nestml.nestml.txt](https://github.com/nest/nestml/files/4104259/traub_ampa_nestml.nestml.txt)
[example_traub_ampa_coupled_neuron.py.txt](https://github.com/nest/nestml/files/4104265/example_traub_ampa_coupled_neuron.py.txt)

**Comment by clinssen** [comment]
Could you try using numbers (1 and 2) instead of strings ("AMPA" and "NMDA") for the "receptor_type"?

**Comment by Ziaeemehr** [comment]
@clinssen Thank you very much, It worked!
