### ISSUE TITLE
Fix print, println functions

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#533]

**Comment by pnbabu** [comment]
Currently, `print` and `println` functions are registered with NESTML but the corresponding C++ code for NEST is not generated.
Thus, C++ code with `cout` should be generated for these print functions.

Following are some initial print statements and the corresponding C++ code which has to be generated.

NESTML print for a simple string:
`print("Hello World")`

Generated C++ code:
`std::cout << "Hello World";`

NESTML print with variables
`print("Value = {var}")`

C++: Anything within the `{ }` has to be considered as a variable and the code has to be generated accordingly
`std::cout << "Value = " << var;`

NESTML println
`println("Hello World")`

Generated C++ code:
`std::cout << "Hello World" << endl;`

More cases could be added as we progress.
