### ISSUE TITLE
ANTLR warning

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#540]
Executing NESTML, I get lots of warning from ``antlr4-python3-runtime`` telling me:

    ANTLR runtime and generated code versions disagree: 4.8!=4.7.1

My guess is that this comes from stored generated files in the NESTML repo (e.g. [here](https://github.com/nest/nestml/blob/b100560aa1b4cfd32fec06e32bcaf6bf7e0eb2ec/pynestml/generated/PyNestMLParserVisitor.py#L1)).
Would it be possible to remove those generated files (regenerate during first call to NESTML on the user's computer) or document a way to remove the warning?
This makes the NESTML output completely unreadable ^^"

**Comment by sternj98** [comment]
Hello, I am just getting started with nestml and am running into this issue trying to run the example script: 

from pynestml.frontend.pynestml_frontend import to_nest, install_nest

to_nest(input_path="/home/nest/work/pynestml/models", target_path="/home/nest/work/pynestml/target")

install_nest("/home/nest/work/pynestml/target", "/home/nest/work/nest-install")

nest.Install("aeif_cond_alpha.nestml") 

Is there any way to turn this error warning off locally?

**Comment by clinssen** [comment]
@sternj98: this issue has been fixed very recently in the master branch. If you are using the latest release (e.g. if you did `pip install nestml`), you are on a slightly older version that does not yet include the fix. I would recommend to use the latest master version. Please see the installation instructions for how to, and let us know if you run into any further issues!

**Comment by sternj98** [comment]
Thank you so much, cloning directly from the master branch worked great! I have been having a good deal of trouble figuring out one other c++ problem if you might be able to give some guidance. Again, trying to run the same example script, I get a cmake error upon calling

install_nest("...nestml/target", "/anaconda3/pkgs/nest-simulator-2.20.0-nompi_py38h8ffda2a_103"):

-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:98 (project):
  The CMAKE_CXX_COMPILER:

    /usr/local/miniconda/conda-bld/nest-simulator_1581420773715/_build_env/bin/x86_64-apple-darwin13.4.0-clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

Is this a purely c++ problem or something that I need to figure out with my installation of Nest? Thank you so much for your help.

**Comment by clinssen** [comment]
For notes on conda installation, please see whether this might be of help: https://github.com/nest/nestml/issues/523

**Comment by sternj98** [comment]
Thank you! This thread seems to capture exactly what is going wrong, sorry for not finding it myself.

**Comment by clinssen** [comment]
We are working on merging this information into a major documentation update, which should make it easier to find in a couple of weeks. Please let us know if you run into any more issues in the meantime!

**Comment by jougs** [comment]
@sternj98: Good that things work now for you :smile:

For the future, please keep separate things separate by either opening a new issue or first asking on the [NEST User Maiing List](https://www.nest-simulator.org/mailinglist/postorius/lists/users.nest-simulator.org/) for advice. Writing in a closed issue has a good potential of being missed and causing more frustration than necessary. Thanks!

**Comment by Silmathoron** [comment]
Should we not keep this issue opened until a long term solution is found? I think this would reduce the number of duplicates.
I'd mark previous messages as off-topic.

**Comment by clinssen** [comment]
This is actually quite tricky, as the error is printed to console by the Antlr runtime rather than going through an error handler:

https://github.com/antlr/antlr4/blob/2ba38605b949a3208230d2c63d2896e035c36723/runtime/Python3/src/antlr4/Recognizer.py#L40

So overriding the error handler (as we are already doing for other reasons) cannot fix this. We could actually manually remove the call to the version checking function in PyNestMLLexer.py and PyNestMLParser.py, but that is a really ugly solution. I think that a clean solution should be submitted upstream (https://github.com/antlr/antlr4), but they might reject this, as having the version incompatibility could lead to undefined behaviour. I think our current solution (upgrade, regenerate the lexer/parser, and tell our users to upgrade their runtimes) is an acceptable solution.

Regenerating the lexer/parser upon NESTML installation is sadly not feasible, as it requires the Java runtime environment, which I'm not ready to add to the NESTML dependencies list.

**Comment by Silmathoron** [comment]
> We could actually manually remove the call to the version checking function in PyNestMLLexer.py and PyNestMLParser.py, but that is a really ugly solution.

Could you elaborate? Do you mean just removing the ``# Generated from PyNestMLLexer.g4 by ANTLR 4.8``?
If so, then having this done and checked automatically by travis seems a lot better to me than having to:
* upgrade
* regenerate the lexer/parser
* tell our users to upgrade their runtimes

> I think that a clean solution should be submitted upstream (https://github.com/antlr/antlr4), but they might reject this, as having the version incompatibility could lead to undefined behaviour.

I would not do it because I don't know ANTLR, so I can't really say but wouldn't it be possible to add an option for skipping version check there?

@jougs any thoughts on that?

**Comment by clinssen** [comment]
Closing this as the only apparent solution is to make sure ANTLR toolchain and runtime versions are matched.
