### ISSUE TITLE
[Error] Package and its compatibility with dependencies

### ISSUE THREAD

**Issue by babsey** [nest/nestml#553]
I was not able to install nestml v3.1 (pip3 install nestml==3.1).
Thus, I installed nestml with pip3 (3.0.post0.dev5). 

When I ran nestml to build neuron models, it produces error because of odetoolbox (v2.0) and sympy (v1.6).
Thus, I have to install older version of these packages:
```
odetoolbox==1.0
sympy==1.5 
```

**Comment by clinssen** [comment]
Thanks for your report!

Unfortunately, sympy 1.6 introduced a significant performance regression. I am trying to address this upstream. For now, we should stick to sympy<=1.5.

The latest NESTML release (3.1) is currently behind the latest ODE-toolbox release (2.0). We hope to release NESTML 4.0 in the upcoming weeks (but probably not before the NEST Conference), which will be compatible with ODE-toolbox 2.0.

**Comment by clinssen** [comment]
SymPy 1.6.1 has been released which fixes the regression. #556 additionally corrects the ODE-toolbox version number in requirements.txt.
