### ISSUE TITLE
Issues in gsl_reference_converter script

### ISSUE THREAD

**Issue by Silmathoron** [nest/nestml#564]
On latest master (4fa0c499f1379cda89722b3dcf55dfc75a9c19f3), there are several issues in the GSL script at ``pynestml/codegeneration/gsl_reference_converter.py``:

* it is missing ``from pynestml.utils.logger import Logger, LoggingLevel``
* nonexisting ``variable`` is accessed on [lines 69-70](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/gsl_reference_converter.py#L69); I would change it to ``ast_variable`` I think but I'm not sure...

EDIT: after testing, ``ast_variable`` seems to be the way to go @clinssen do you want me to make a PR or are you already working on this file?

**Comment by clinssen** [comment]
We're planning to merge #515 later this week in the lead-up to NESTML 4.0 with the new ODE-toolbox. It looks like the changes you proposed are already fixed there. Sorry for taking so long with this PR!

**Comment by Silmathoron** [comment]
Great, can you add the "fixes" magic keyword in a new comment in #515, then?
