### ISSUE TITLE
Rename shape to kernel

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#570]
Whenever I need to explain the concept of a "shape" to somebody, it seems that as soon as I say it's a kernel, that can subsequently be used in convolutions, the other party immediately has an "aha!-Erlebnis". I would suggest to rename the shape keyword to "kernel". Discussion/thoughts welcome!

**Comment by Silmathoron** [comment]
That's fine with me, but I think we should deprecate ``shape`` will still supporting it in the next major release, otherwise this is going to break a lot of code
