### ISSUE TITLE
Fix pygments syntax highlighting for multiline C-style comments

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#578]
C-style comment (``/* ... */``) syntax highlighting is currently broken in Pygments, which affects the documentation on readthedocs.

Either we should fix the custom NESTML Pygments lexer, or remove C-style comments completely. (We already replaced them with Python-style triple-quotes in models files some time ago.)

**Comment by Silmathoron** [comment]
I thought we decided to remove them in a previous discussion.
I would again promote that solution ;)

**Comment by jougs** [comment]
I'm still not sure how we should handle model documentation. If I'm not mistaken, the docs are still enclosed in C-style comments. An option would be to have documentation enclosed in triple quotes the same way that a module-level docstring would be.

**Comment by Silmathoron** [comment]
@jougs what docs are you referring to?

**Comment by jougs** [comment]
The ones at the top of the file. But after checking the current code, I realized that everything already is as I'm proposing! I thus suggest that you forget anything I said and I completely agree with removing support for C-style comments.

**Comment by clinssen** [comment]
Great, thanks for the discussion! I think single-triple-quotes are still missing from the NESTML grammar. So I will file a PR to allow both ``"""`` and ``'''`` for multiline comments, and removing the remaining mentions of ``/* ... */`` from the documentation.

**Comment by clinssen** [comment]
- For model documentation: special case (PEP 257-like) docstrings at very top of model
- N.B. triple-quoted NESTML strings are not actually strings, but comments!
