### ISSUE TITLE
Remove workaround for NEST Simulator bug

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#581]
Undo https://github.com/nest/nestml/pull/515/commits/b34c3e2d0fdad05dacd285651eb8691db718555e and https://github.com/nest/nestml/pull/515/commits/297d460a6eb3b7e6ab0e3f06fc4829526979afad.

@jougs: do you know whether an upstream issue for this already exists? If not, should this be filed under https://github.com/nest/nest-simulator or https://github.com/nest/nest-extension-module?

**Comment by jougs** [comment]
Is this referring to the issue caused by #1748, where the includes are not found anymore?

**Comment by clinssen** [comment]
Yes, that's exactly it. It looks like there isn't a GitHub issue yet for this.

**Comment by jougs** [comment]
Thanks for the clarification. Yes, I think you can add an issue describing the problem.

**Comment by jougs** [comment]
The problem is caused by a change in NEST solely, thus the issue should go to https://github.com/nest/nest-simulator https://github.com/nest/nest-simulator.
