### ISSUE TITLE
Merge ``state`` and ``initial_values`` blocks into ``state`` block

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#634]
It is unclear why there is a distinction to begin with.

The ``state`` block should allow declaration of variables both with and without an initial value.

Ideally, for variables that are not assigned an initial value, it is checked that on all possible execution paths, they are written to before being read.

**Comment by jougs** [comment]
Would it help if we introduced a new keyword (e.g. `auto`) for situations, where the user does not want to provide an initial value? I seem to remember that [ODE-toolbox](https://github.com/nest/ode-toolbox) can actually generate them under some circumstances. Having a special keyword would make that choice explicit.

If this is not feasible, we should probably just go with what we discussed earlier, e.g. to require an initial value for every variable in the `state` block.
