### ISSUE TITLE
Adapt NESTML to NEST3 random number generator features

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#644]
Random number generation in NEST Simulator will be refactored for the NEST 3.0 release. These changes are not yet merged at time of writing (https://github.com/nest/nest-simulator/pull/1549). The NESTML 4.0 release should make sure that these upcoming RNG changes are included.

**Comment by clinssen** [comment]
Removing the NESTML 4.0 milestone after discussion; if NEST 3.0 is out before NESTML 4.0, this issue should be resolved before release, but it should not hold up release of NESTML 4.0.

**Comment by pnbabu** [comment]
Since the new random number generator is already in NEST master, we can adapt the changes for NESTML 4.0 release. PR with changes - #650
