### ISSUE TITLE
Replace synapse event handler block names with ``onEvent()``

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#662]
Use ``onEvent(in_port_name)`` instead of ``preReceive`` and ``postReceive`` in synapse event handler block names, as this mechanism is more generic and requires less extra NESTML syntax. Compare

```
input:
    pre_spikes nS <- spike
    post_spikes nS <- spike
end

preReceive:
    # [...]
end

postReceive:
    # [...]
end
```

and

```
input:
    pre_spikes nS <- spike
    post_spikes nS <- spike
end

onReceive(pre_spikes):
    # [...]
end

onReceive(post_spikes):
    # [...]
end
```

**Comment by clinssen** [comment]
Discussion: do we prefer ``onEvent``, ``onReceive``, ``onSpike``, ...?

**Comment by jougs** [comment]
... over what?

**Comment by clinssen** [comment]
Right now we have ``preReceive`` and ``postReceive``, but these should be replaced with ``EVENT_HANDLER_BLOCK_KEYWORD(input_port_name)``, because this is more flexible and provides some groundwork for expressing the timing of how simultaneously-arriving events should be handled. The discussion point is: should ``EVENT_HANDLER_BLOCK_KEYWORD`` be one of ``onEvent``, ``onReceive``, ``onSpike``, or something different?

**Comment by clinssen** [comment]
Done in https://github.com/nest/nestml/pull/655/commits/353836ec2920958c3193998130098d8f4ca1ac5b.
