### ISSUE TITLE
Rendering of Izhekevich tutorial is broken

### ISSUE THREAD

**Issue by med-ayssar** [nest/nestml#677]
- The [Izhekevich tutorial page](https://nestml.readthedocs.io/en/latest/tutorials/izhikevich/nestml_izhikevich_tutorial.html) is not rendered properly on Read the Docs, leading to a display of the raw JSON objects instead of rendered cells. The same is true for all other turorials.
- There I have highlighted a typo in the first section of PyNestml [rocessing != processing](https://nestml.readthedocs.io/en/latest/pynestml_toolchain/front.html#:~:text=Checks%20conclude%20the-,rocessing,-by%20checking%20the)

**Comment by jougs** [comment]
Thanks for your report.

> In the following, I have highlighted the typo in the first section of PyNestml [rocessing != processing](https://nestml.readthedocs.io/en/latest/pynestml_toolchain/front.html#:~:text=Checks%20conclude%20the-,rocessing,-by%20checking%20the)

Can you please send a PR to fix this?

**Comment by med-ayssar** [comment]
By the way, it is not only the "Izhekevich" page. All the tutorial pages are having the same issue.

**Comment by pnbabu** [comment]
@med-ayssar I am currently fixing the tutorials page. A pull request is on its way. 
Could you raise a pull request for the typo as @jougs pointed out?
