### ISSUE TITLE
`ASTNeuron.clone` is not working properly

### ISSUE THREAD

**Issue by med-ayssar** [nest/nestml#725]
**Describe the bug**
Assuming directly after parsing the `ǹestml` files, you create a `deepcopy` with `ASTNeuron.clone` function, and then we proceed with calling the `CodeGenerator` to `transfrom` the `neurons` and `synapses`. Using the `clone` function, we should assume that the first instance won't be modified if the cloned version introduces new changes, but the problem here that the original instance will be modified as well.
**To Reproduce**
1. Get the parsed `ASTNeuron` and `ASTSynapse` instances without applying any modification
2. Call `neuron.get_internal_symbols() ` 
2. Call the `clone` function on each instance
3. Call the `analyse_transform` function on the cloned instances
4. Call again `neuron.get_internal_symbols() ` on the original version and the cloned version
5. Result: in Step 4, both original and cloned version return same objects, whereas in Step 2 we see different object
 * We expect the original to always return the same result

**Additional context**
Using `copy.deepcopy` doesn't fix the problem, as we get the following error when trying to run the `deepcopy` on the `Scope` instance: `cannot pickle '_io.textiowrapper' object`

**Comment by clinssen** [comment]
``clone()`` only clones the AST nodes, but not the symbols. You should run a symbol table update after modifying the AST.
