### ISSUE TITLE
Split `nestml` code generation phases

### ISSUE THREAD

**Issue by med-ayssar** [nest/nestml#739]
Executing `generate_taget`, it calls the `nestml` code generation pipeline without having independent functions to separate the code generation phases. Mainly, the pipeline should  have four stages, `parse,  transform, generate_code`, and `build`. For the `JIT` project, we need to have control over these phases and not calling them in one block. Therefore, `JIT` must split between two (parsing, transforming) and (generating code, building). 

A use case would be generating the `neuron_synapse` code from a previously seen `neuron` model, however in that particular face we have `moving` variables from the `synapse` model to `ǹeuron` model, and the responsible function for inserting new variable in the `ǹeuron` class is done inside the transformation phase, and thus we must have a separate function to transform the `AstNeuron" before going to the code generation.

**Comment by clinssen** [comment]
I think this is a great idea, but we should additionally split off the transformation steps into a separate class ``Transformer``, akin to ``Builder``.
