### ISSUE TITLE
Uncompleted code generation when using `array` in nestml

### ISSUE THREAD

**Issue by med-ayssar** [nest/nestml#758]
The following problem happens only when using `array` state attributes in nestml.

- Assuming we have this simple nestml code:
```
neuron simple_model:
  state:
   g_ex [20] real = 1.2
  end
end
```
the resulted code has a small issue in the header file and precisely in the `get_state_element` function:

```
inline double get_state_element(size_t elem)
  {
    if
    {
      return S_.g_ex[ elem - State_::G_EX];
    }
  }
```
The condition seems to be missing in the generated code.

**Comment by clinssen** [comment]
@pnbabu: could you look into this? Cheers!

**Comment by med-ayssar** [comment]
FYI: Interestingly, if we have two arrays, the code generation for that function works pretty fine.

**Comment by pnbabu** [comment]
@med-ayssar yes, I tested that too. We already have a test with multiple vectors which works fine. It's only an issue with a single vector. Thanks for finding this bug! I will have a look at it.
