### ISSUE TITLE
Problem importing NESTML 5.0.0 

### ISSUE THREAD

**Issue by ewa8** [nest/nestml#762]
Hi, I’ve tried using the newest version of NESTML but even right at the import of 'generate_nest_target' I experienced the following error:

<img width="820" alt="Screenshot 2022-04-23 at 08 29 29" src="https://user-images.githubusercontent.com/53698771/164882975-de6c8ec1-5577-408d-8070-8044048f00eb.png">

<img width="1058" alt="Screenshot 2022-04-23 at 08 29 59" src="https://user-images.githubusercontent.com/53698771/164882989-e469e1c6-fc88-4c77-b967-42d245a9725b.png">

I’m running Python version 3.10.2, NEST 3.3 and NESTML 5.0.0-rc2 and using a Mac with the Apple chip. 

I also tried downloading the NESTML 4.0 version and while I do manage to import the ‘to_nest’ function and successfully run it, I instead run into the following problem when running the ‘make’ command from the target directory to assemble the module. 

<img width="756" alt="Screenshot 2022-04-23 at 08 25 50" src="https://user-images.githubusercontent.com/53698771/164882873-61e38a59-d7ce-4456-8d9f-0a4223bc18ab.png">

**Comment by clinssen** [comment]
To fix this problem, please install the latest version of the Python package ``antlr4-python3-runtime``, using, for example:

```sh
python3 -m pip install antrl4-python3-runtime --upgrade
```

This should get you version 4.10. I've updated this requirement in 71d92964eb47740b6d3a19746028a05a2a31a8ca. Please let us known if this solves the problem for you. Many thanks!

**Comment by ewa8** [comment]
It worked perfectly, thank you so much!
