### ISSUE TITLE
Error with vector initialisation

### ISSUE THREAD

**Issue by ewa8** [nest/nestml#767]
Hi, when running 'generate_nest_target' on a NESTML file I created I get the following error:
![Screenshot 2022-04-26 at 16 45 53](https://user-images.githubusercontent.com/53698771/165327166-5255d7bf-7f95-42af-863d-ad7b1310c0c4.png)

I assume it refers to the vectors I defined and initialized in the parameters block of my file, where I followed the instructions on how to do it from the documentation:
![Screenshot 2022-04-26 at 16 46 37](https://user-images.githubusercontent.com/53698771/165327334-8e67d487-1a20-4012-9358-7c06dc6321cc.png)

**Comment by clinssen** [comment]
Could you try defining the length of the vector as a parameter for now (``N int = 3``)?

@pnbabu: could you look into this when you're back from vacation? Thanks!

**Comment by ewa8** [comment]
The problem persists when defining the length of the vector as a parameter. If I additionally then move the definition of the vectors to the state block instead of the parameters I get the following error instead:

![Screenshot 2022-04-28 at 11 12 18](https://user-images.githubusercontent.com/53698771/165719409-2c39583f-eee4-41aa-85e5-928b43700258.png)

**Comment by pnbabu** [comment]
@ewa8 Apologies for the delayed reply. Could you share the NESTML model you created? Which version of NESTML are you using?
