### ISSUE TITLE
Active dendrite tutorial not reproducible & fixed behavior on first run

### ISSUE THREAD

**Issue by francesshei** [nest/nestml#774]
I couldn't replicate the results reported in the active dendrite tutorial found on the documentation (https://nestml.readthedocs.io/en/latest/tutorials/active_dendrite/nestml_active_dendrite_tutorial.html). 

Specifically, when copy-pasting the code and evaluating the neuron using the first parameters reported (`neuron_parms={"I_th": 100., "I_dAP_peak": 400.}`), the membrane voltage value is clamped to 0: 

![Figure_1](https://user-images.githubusercontent.com/39373100/167132668-8e8a5bb6-b3c6-4839-8240-04ccfeaf434b.png)

While running `evaluate_neuron` with the default NESTML code parameters saturates the spiking activity: 

![Figure_2](https://user-images.githubusercontent.com/39373100/167132743-ac67425f-d91e-4760-b2d0-2cb8e8f2c4e2.png)

The high threshold results, instead, are coherent with the tutorial: 
 
![Figure_3](https://user-images.githubusercontent.com/39373100/167132831-f22a16b1-22dc-4415-91d4-9fe09bb5d197.png)

On a side note, the first run of the script always produces the first figure (even when varying the arguments of `evaluate_neuron`), while executing the script in an interactive session (i.e., `python -i [my_file.py]`) to keep the variables loaded after the first run allows to change the parameters used in the simulations when calling the `evaluate_neuron` function.

NEST version: `master-01f6e5a76`
NESTML version: `5.0.0-rc2`
Running on MacOS 12.3.1

**Comment by clinssen** [comment]
Hi, sorry, this does indeed seem to be a bug! It looks like it's a bug with ODE-toolbox, please stand by while we fix it in there.

Meanwhile, a workaround would be to include the parameter ``disable_analytic_solver=True`` in the call here: https://github.com/nest/nestml/blob/master/pynestml/codegeneration/nest_code_generator.py#L1197.

**Comment by clinssen** [comment]
An upstream fix is being developed: https://github.com/nest/ode-toolbox/pull/60
