### ISSUE TITLE
NESTML import fails antlr4 issue

### ISSUE THREAD

**Issue by tfardet** [nest/nestml#775]
Installing nestml4 from pip, the following code fails:

```python
from pynestml.frontend.pynestml_frontend import to_nest, install_nest
```

with the following error:
```
~/.local/lib/python3.10/site-packages/antlr4/atn/ATNDeserializer.py in checkVersion(self)
     50             print(version, SERIALIZED_VERSION)  # this is None and 4
     51             print(self.data[0:self.pos+100]) # this is mostly newlines and things that render as whitespaces, in particular at self.pos
---> 52             raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
     53 
     54     def readATN(self):

Exception: Could not deserialize ATN with version  (expected 4).
```

Issue occurs with Python 3.10.4, antlr4-python3-runtime 4.10, and pynestml 4.0.0

The file failing the check is ``pynestml/generated/PyNestMLLexer.py``, which reads: ``# Generated from PyNestMLLexer.g4 by ANTLR 4.9.1``.
Running ``pip install --force antlr4-python3-runtime==4.9`` solves the issue but it would probably be a good idea to not depend on antlr's version if possible.

**Comment by clinssen** [comment]
Hi @tfardet! We're about to release NESTML 5.0. In the mean time, please pip install NESTML using the ``--pre`` flag (see https://nestml.readthedocs.io/en/v5.0.0-rc2/installation.html).

**Comment by tfardet** [comment]
Thanks @clinssen will check 5.0.
Does 5.0 solve the antlr problem issue? (and by that I mean *permanently*, not just "at the moment because it was generated with 4.10")

**Comment by clinssen** [comment]
The trouble is that the antlr4 runtime (coming from PyPI) could be of a different version than the antlr4 Java application that was used to generate the lexer and parser. Bundling the latter with every NESTML install is obviously too heavyweight. We could pin the antlr4-runtime version number in requirements.txt to be <=4.10 to prevent accidental breakage when antlr release a new version upstream.

**Comment by tfardet** [comment]
I think pinning the version would be good if the different versions are incompatible and the check cannot be skipped via an argument passed to antlr.
Note that you might have to pin the exact version (==4.10) since 4.9 and 4.10 did not seem to be compatible (at least 4.10 does not read 4.9).
