### ISSUE TITLE
nestml Izhikevich tutorial fails using conda/pip build but succeeds using docker

### ISSUE THREAD

**Issue by dnao** [nest/nestml#799]
I've been trying to run the [Izhikevich tutorial](https://nestml.readthedocs.io/en/v5.0.0/tutorials/izhikevich/nestml_izhikevich_tutorial.html) as a test of whether nestml is installed correctly. It runs successfully on the Docker image on my local machine but when I try it on a fresh conda build on a HPC with nestml installed via pip (as per instructions [here](https://nestml.readthedocs.io/en/latest/installation.html)) it fails. I've attached the output file showing the errors:
[conda_output.txt](https://github.com/nest/nestml/files/9168157/conda_output.txt)

System is HPC running RHEL6 with the 2.6.32-696.16.1.el6.x86_64 kernel and the following software versions:

cmake/3.21.1
gsl/1.16
gcc/12.1.0
openmpi-intel/1.8.4

**Comment by dnao** [comment]
I just realised that the previous build was using nest-2.20.2

I've tried to run it again using nest-3.3 but it also gives an error.

I've attached the output as well as the packages installed in the environment.
[headnode_output.txt](https://github.com/nest/nestml/files/9169451/headnode_output.txt)
[packages.txt](https://github.com/nest/nestml/files/9169452/packages.txt)

**Comment by clinssen** [comment]
@steffengraber: could you perhaps check the conda environment? Cheers!

**Comment by pnbabu** [comment]
@dnao thanks for writing in. NEST 3.3 is unfortunately not compatible with NESTML 5.0.0. We have observed some inconsistencies with the versioning between the two and are trying to fix it: https://github.com/nest/nestml/pull/800

Meanwhile, would it be possible for you to install the latest NEST master from source (https://nest-simulator.readthedocs.io/en/v3.3/installation/index.html#advanced-install) and also use the latest NESTML (using `pip install git+https://github.com/nest/nestml.git`)? Please let us know if you run into any issues with this.

**Comment by dnao** [comment]
Hi @pnbabu thank you for the assistance. I have been trying to compile NEST from source but have been having issues as well: https://github.com/nest/nest-simulator/issues/2431.

**Comment by dnao** [comment]
Thank you for your assistance. I managed to compile nest after switching to the latest version of gcc. After installing nestml using pip, it appears to be working correctly.
