### ISSUE TITLE
Mechanisms to list and uninstall nestml-generated nest modules

### ISSUE THREAD

**Issue by WillemWybo** [nest/nestml#815]
A mechanisms to detect whether the `*.so` associated with a given nestml-module is still present in `<path to nest build>/lib/nest/` would be very helpful and avoid potential bugs where an old version of a module may still be installed unknowingly.

Potential easy solution:
Have `generate_nest_target()` return the path to the `*.so` file. The string certainly exists somewhere, as it is printed after successfull model compilation.

**Comment by med-ayssar** [comment]
The NESTML model is either installed by default in the `<path to nest build>/lib/nest/`, or in the `install_dir` if it was given in the `generate_nest_target` as one of the arguments. So could you maybe elaborate more your issue?

**Comment by WillemWybo** [comment]
Is there a standard way to get this path `<path to nest build>/lib/nest/` from within python (e.g. a function that returns it)? That would already solve the issue. It would be even better to have a function that returns all paths where NESTML models are installed. Then, it's easy to get an overview of which models actually are installed on the system. 

I would like to implement an automatic check to test whether a model is installed, in order to avoid regenerating it, as this takes a lot of time.

**Comment by clinssen** [comment]
Perhaps the call ``nest.ll_api.sli_func("statusdict/prefix ::")`` would be of use? It returns the NEST installation directory, so you would just have to ``os.path.join()`` it with ``lib/nest``. Optionally we could wrap this in the ``NESTTools`` class.

To check if a model is installed, you could potentially also use ``nest.node_models``, which returns the names of all known node (neuron) models.

**Comment by med-ayssar** [comment]
I think what he is looking for is something like the same thing I did in my `JIT` project.  He wants to know which unloaded library has the desired model.

**Comment by jougs** [comment]
Can this be closed? @WillemWybo, are the explanations by @med-ayssar and @clinssen sufficient?

**Comment by WillemWybo** [comment]
@jougs The explanations certainly resolve my problem. 

However, I do like the suggestion by @clinssen of wrapping `nest.ll_api.sli_func("statusdict/prefix ::")` call in the NESTTools class into something with a logical name (something like `get_default_module_installation_path()`). Furthermore, I think the docs page [https://nestml.readthedocs.io/en/latest/running.html](https://nestml.readthedocs.io/en/latest/running.html) could make it more clear what the difference between `target_path` and `install_path` is (basically, the only explanation there is under the section *Running NESTML from the command line*, which I did not read because I'm not running NESTML from the command line). A final suggestion would be to have the install path default to the target path, so that by default all generated stuff is in the same location (this would be convenient for the way in which I'm using it, but possibly not for other use cases / backwards compatibility).

**Comment by WillemWybo** [comment]
I was merely making these suggestion from a user perspective. For me personally the problem is solved entirely.

**Comment by jougs** [comment]
Alright. Thanks for the clarification. Then I'll close this issue, as the simplified access to these "hidden" kernel parameters will come anyway.
