### ISSUE TITLE
Unable to compile neuromodulated STDP synapse

### ISSUE THREAD

**Issue by ewa8** [nest/nestml#833]
Hi, I tried running the following code from the NESTML dopamine-modulated STDP synapse tutorial with my own neuron module (which I have previously tested and can be compiled and installed in NEST):

`module_name, neuron_model_name, synapse_model_name = \
    generate_code_for("nest_module/snr.nestml",
                      "nest_module/neuromodulated_stdp.nestml",
                      post_ports=["post_spikes"],
                      mod_ports=["mod_spikes"])`

and I got the following error:

nestml_180c32c25bde495cbc0827e3b7a400b9_module Configuration Summary

C++ compiler         : /usr/bin/clang++
Build static libs    : OFF
C++ compiler flags   : 
NEST compiler flags  :  -O2 -std=c++11 -Wall -Xclang -fopenmp  -O3 -DNDEBUG
...
14 warnings and 2 errors generated.
make[2]: *** [CMakeFiles/nestml_180c32c25bde495cbc0827e3b7a400b9_module_module.dir/nestml_180c32c25bde495cbc0827e3b7a400b9_module.o] Error 1
make[1]: *** [CMakeFiles/nestml_180c32c25bde495cbc0827e3b7a400b9_module_module.dir/all] Error 2
make: *** [all] Error 2
Output exceeds the size limit. Open the full output data in a text editor
CalledProcessError                        Traceback (most recent call last)
File /opt/homebrew/lib/python3.10/site-packages/pynestml/codegeneration/nest_builder.py:151, in NESTBuilder.build(self)
    150 try:
--> 151     subprocess.check_call(make_all_cmd, stderr=subprocess.STDOUT, shell=shell,
    152                           cwd=str(os.path.join(target_path)))
    153 except subprocess.CalledProcessError as e:

File /opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:369, in check_call(*popenargs, **kwargs)
    368         cmd = popenargs[0]
--> 369     raise CalledProcessError(retcode, cmd)
    370 return 0

CalledProcessError: Command '['make', 'all']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

GeneratedCodeBuildException               Traceback (most recent call last)
/Users/ewarusiecka/Documents/University/DTU/Special_course/MSN/01 - General behaviour.ipynb Cell 7 in <cell line: 3>()
      1 # generate and build code
      2 module_name, neuron_model_name, synapse_model_name = \
----> 3     generate_code_for("nest_module/snr.nestml",
      4                       "nest_module/neuromodulated_stdp.nestml",
      5                       post_ports=["post_spikes"],
      6                       mod_ports=["mod_spikes"])
...
--> 154     raise GeneratedCodeBuildException('Error occurred during \'make all\'! More detailed error messages can be found in stdout.')
    156 # finally execute make install
    157 try:

GeneratedCodeBuildException: Error occurred during 'make all'! More detailed error messages can be found in stdout.

Additionally, I tried running the code with the iaf_psc_delta neuron model just like it is shown in the tutorial to make sure it is not my neuron model throwing the error but I just got this error instead:

Exception                                 Traceback (most recent call last)
/Users/ewarusiecka/Documents/University/DTU/Special_course/MSN/01 - General behaviour.ipynb Cell 7 in <cell line: 3>()
      1 # generate and build code
      2 module_name, neuron_model_name, synapse_model_name = \
----> 3     generate_code_for(iaf_psc_delta,
      4                       "nest_module/neuromodulated_stdp.nestml",
      5                       post_ports=["post_spikes"],
      6                       mod_ports=["mod_spikes"])

/Users/ewarusiecka/Documents/University/DTU/Special_course/MSN/01 - General behaviour.ipynb Cell 7 in generate_code_for(nestml_neuron_model, nestml_synapse_model, post_ports, mod_ports, uniq_id, logging_level)
     51 # generate the code for neuron and synapse (co-generated)
     52 module_name = "nestml_" + uniq_id + "_module"
---> 53 generate_nest_target(input_path=[neuron_uniq_fn, synapse_uniq_fn],
     54                      logging_level=logging_level,
     55                      module_name=module_name,
     56                      suffix="_nestml",
     57                      codegen_opts={"neuron_parent_class": "StructuralPlasticityNode",
     58                                    "neuron_parent_class_include": "structural_plasticity_node.h",
     59                                    "neuron_synapse_pairs": [{"neuron": neuron_model_name_uniq,
     60                                                              "synapse": synapse_model_name_uniq,
     61                                                              "post_ports": post_ports,
     62                                                              "vt_ports": mod_ports}]})
     63 mangled_neuron_name = neuron_model_name_uniq + "_nestml__with_" + synapse_model_name_uniq + "_nestml"
     64 mangled_synapse_name = synapse_model_name_uniq + "_nestml__with_" + neuron_model_name_uniq + "_nestml"
...
--> 432     raise Exception("Neuron name used in pair ("" + neuron_name + "") not found")  # XXX: log error
    433     return neurons, synapses
    434 neuron = neurons[neuron_names.index(neuron_name + FrontendConfiguration.suffix)]

Exception: Neuron name used in pair ( + neuron_name + ) not found

Any idea what it might be caused by or how I could otherwise compile the STDP synapse with my neuron model?

**Comment by clinssen** [comment]
Hi, thanks for your error report. This is an error we were seeing earlier on MacOS systems, which was caused when a script was calling ``generate_nest_target()`` without this call being enclosed in an ``if __name__ == "__main__"`` block. But it would be strange if this was also happening from within Jupyter notebooks.

Could you check that you are running the latest version of NESTML (optionally, do a ``pip install git+https://github.com/nest/nestml --upgrade``)?

@pnbabu: could you see if you can replicate this error, as you also have a Mac system?

**Comment by ewa8** [comment]
Hi, I upgraded to the latest version but unfortunately the same error persists

**Comment by clinssen** [comment]
Thanks for testing that. Could I ask you to do the following:

- The actual errors are not shown in the logs, only that an error occurred. Could you run ``generate_nest_target()`` with run with logging_level="DEBUG"?
- Could you post the full (non abbreviated) logs?
- Could you send us the model (via email would be fine) so that we can try to reproduce the issue locally?

Cheers!

**Comment by clinssen** [comment]
@ewa8: thanks for the detailed report! The error is buried pretty deep in there. The issue that for NEST Simulator, each synapse model needs to have one particular parameter that specifies the synaptic delay and is decorated with the string ``@nest::delay``. This is right now missing from your model, it should work if you add that. (Please see the existing synapse models in ``models/synapses/*.nestml`` for examples).

To give a more friendly error message in the future, I have created #837.
