### ISSUE TITLE
Remove outdated asserts from NEST templates

### ISSUE THREAD

**Issue by pnbabu** [nest/nestml#878]
Following nest/nest-simulator#2616, the asserts from jinja templates for NEST must be removed.

**Comment by jougs** [comment]
Looking at the [template](https://github.com/nest/nestml/blob/master/pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2#L513), I don't see any such assertions and think this can be closed. Can you please do this and also add a corresponding comment in https://github.com/nest/nest-simulator/pull/2616? Thanks!

**Comment by pnbabu** [comment]
Thanks for checking this. I will close this issue as the assert is not present in the template.
