### ISSUE TITLE
unit of Conductance 

### ISSUE THREAD

**Issue by atiye-nejad** [nest/nestml#923]
I have a silly question. in papers unit of conductance mentions as nS/µm² . but in nestml documents just mentioned nS and it is baffling. may I ask you to let me know the exact unit for conductance that is used in nestml codes? I am going to write a new nestml neuron and try to keep the units the same. thanks.

**Comment by clinssen** [comment]
This depends on the details of the particular model you are trying to reproduce (implement) in NESTML. I would suggest to follow whichever units the original authors used in their paper.
