### ISSUE TITLE
Receptors in weight recorder recorded data is incorrect 

### ISSUE THREAD

**Issue by Maryada-27** [nest/nestml#952]
The receptor set while creating a connection is different from what's observed via weight recorder.

**Comment by jougs** [comment]
Please send a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) that demonstates the problem.

**Comment by pnbabu** [comment]
This must be resolved in the current NESTML release. Please feel free to reopen this if the issue persists.
