### ISSUE TITLE
Add non-default install path option to ``NESTCodeGeneratorUtils.generate_code_for()``

### ISSUE THREAD

**Issue by clinssen** [nest/nestml#972]
On the EBRAINS image, NESTML tries to copy the generated .so user extension module into the NEST Simulator install directory, which is not writeable by the user. 

Add a feature to install this to another location, or use mkstemp to automatically find a suitable location.

**Comment by pnbabu** [comment]
We have the option to install the binaries to another location via the `install_path` argument to the `generate_target()` function. This is used in [this notebook](https://github.com/nest/nestml-examples/blob/main/nestml-hello-world.ipynb) which runs fine with the recent `EBRAINS-23.09-rc2` image for EBRAINS.

**Comment by clinssen** [comment]
Yes, but all tutorial notebooks currently use ``NESTCodeGeneratorUtils.generate_code_for()``. We indeed just have to pass the parameter in the right way—or have ``generate_code_for()`` generate a temporary directory (using mkstemp) if the supplied ``install_path`` equals ``None``.

**Comment by terhorstd** [comment]
I've added the `install_path` to the [notebook](https://github.com/nest/nestml-examples), so that it passes the tests.
