### ISSUE TITLE
Check for ANTLR runtime 4.10.1 but 4.13 is installed via requirements.txt

### ISSUE THREAD

**Issue by steffengraber** [nest/nestml#991]
For me, this message appears in `nestml v7.0.0`:

> ANTLR runtime and generated code versions disagree: 4.13.0!=4.10.1

But in the `requirements.txt` `antlr4-python3-runtime == 4.13` is required. 

https://github.com/nest/nestml/blob/v7.0.0/requirements.txt

**Comment by clinssen** [comment]
Good point, Steffen, we should ensure that this is consistent. However, it's not a problem in practice, the warnings are annoying but they can be safely ignored.
